// THIS IS AN AUTOMATICALLY GENERATED FILE.
// DO NOT MODIFY BY HAND!!
//
// Generated by zcm-gen

#include <string.h>
#ifndef ZCM_EMBEDDED
#include <stdio.h>
#endif
#include "geometry_msgs/geometry_msgs_PoseStamped.h"

static int __geometry_msgs_PoseStamped_hash_computed = 0;
static uint64_t __geometry_msgs_PoseStamped_hash;

uint64_t __geometry_msgs_PoseStamped_hash_recursive(const __zcm_hash_ptr* p)
{
    const __zcm_hash_ptr* fp;
    for (fp = p; fp != NULL; fp = fp->parent)
        if (fp->v == __geometry_msgs_PoseStamped_get_hash)
            return 0;

    __zcm_hash_ptr cp;
    cp.parent =  p;
    cp.v = (void*)__geometry_msgs_PoseStamped_get_hash;
    (void) cp;

    uint64_t hash = (uint64_t)0xdeae7beebbb41387LL
         + __std_msgs_Header_hash_recursive(&cp)
         + __geometry_msgs_Pose_hash_recursive(&cp)
        ;

    return (hash<<1) + ((hash>>63)&1);
}

int64_t __geometry_msgs_PoseStamped_get_hash(void)
{
    if (!__geometry_msgs_PoseStamped_hash_computed) {
        __geometry_msgs_PoseStamped_hash = (int64_t)__geometry_msgs_PoseStamped_hash_recursive(NULL);
        __geometry_msgs_PoseStamped_hash_computed = 1;
    }

    return __geometry_msgs_PoseStamped_hash;
}

int __geometry_msgs_PoseStamped_encode_array(void* buf, uint32_t offset, uint32_t maxlen, const geometry_msgs_PoseStamped* p, uint32_t elements)
{
    uint32_t pos_byte = 0, element;
    int thislen;

    for (element = 0; element < elements; ++element) {

        /* header */
        thislen = __std_msgs_Header_encode_array(buf, offset + pos_byte, maxlen - pos_byte, &(p[element].header), 1);
        if (thislen < 0) return thislen; else pos_byte += thislen;

        /* pose */
        thislen = __geometry_msgs_Pose_encode_array(buf, offset + pos_byte, maxlen - pos_byte, &(p[element].pose), 1);
        if (thislen < 0) return thislen; else pos_byte += thislen;

    }
    return pos_byte;
}

int geometry_msgs_PoseStamped_encode(void* buf, uint32_t offset, uint32_t maxlen, const geometry_msgs_PoseStamped* p)
{
    uint32_t pos = 0;
    int thislen;
    int64_t hash = __geometry_msgs_PoseStamped_get_hash();

    thislen = __int64_t_encode_array(buf, offset + pos, maxlen - pos, &hash, 1);
    if (thislen < 0) return thislen; else pos += thislen;

    thislen = __geometry_msgs_PoseStamped_encode_array(buf, offset + pos, maxlen - pos, p, 1);
    if (thislen < 0) return thislen; else pos += thislen;

    return pos;
}

uint32_t __geometry_msgs_PoseStamped_encoded_array_size(const geometry_msgs_PoseStamped* p, uint32_t elements)
{
    uint32_t size = 0, element;
    for (element = 0; element < elements; ++element) {

        size += __std_msgs_Header_encoded_array_size(&(p[element].header), 1); // header

        size += __geometry_msgs_Pose_encoded_array_size(&(p[element].pose), 1); // pose

    }
    return size;
}

uint32_t geometry_msgs_PoseStamped_encoded_size(const geometry_msgs_PoseStamped* p)
{
    return 8 + __geometry_msgs_PoseStamped_encoded_array_size(p, 1);
}

uint32_t geometry_msgs_PoseStamped_struct_size(void)
{
    return sizeof(geometry_msgs_PoseStamped);
}

uint32_t geometry_msgs_PoseStamped_num_fields(void)
{
    return 2;
}

int geometry_msgs_PoseStamped_get_field(const geometry_msgs_PoseStamped* p, uint32_t i, zcm_field_t* f)
{
    if (i >= geometry_msgs_PoseStamped_num_fields())
        return 1;
    
    switch (i) {
    
        case 0: {
            /* Header */
            f->name = "header";
            f->type = ZCM_FIELD_USER_TYPE;
            f->typestr = "std_msgs.Header";
            f->num_dim = 0;
            f->data = (void*) &p->header;
            return 0;
        }
        
        case 1: {
            /* Pose */
            f->name = "pose";
            f->type = ZCM_FIELD_USER_TYPE;
            f->typestr = "geometry_msgs.Pose";
            f->num_dim = 0;
            f->data = (void*) &p->pose;
            return 0;
        }
        
        default:
            return 1;
    }
}

const zcm_type_info_t* geometry_msgs_PoseStamped_get_type_info(void)
{
    static int init = 0;
    static zcm_type_info_t typeinfo;
    if (!init) {
        typeinfo.encode         = (zcm_encode_t) geometry_msgs_PoseStamped_encode;
        typeinfo.decode         = (zcm_decode_t) geometry_msgs_PoseStamped_decode;
        typeinfo.decode_cleanup = (zcm_decode_cleanup_t) geometry_msgs_PoseStamped_decode_cleanup;
        typeinfo.encoded_size   = (zcm_encoded_size_t) geometry_msgs_PoseStamped_encoded_size;
        typeinfo.struct_size    = (zcm_struct_size_t)  geometry_msgs_PoseStamped_struct_size;
        typeinfo.num_fields     = (zcm_num_fields_t) geometry_msgs_PoseStamped_num_fields;
        typeinfo.get_field      = (zcm_get_field_t) geometry_msgs_PoseStamped_get_field;
        typeinfo.get_hash       = (zcm_get_hash_t) __geometry_msgs_PoseStamped_get_hash;
    }
    
    return &typeinfo;
}

int __geometry_msgs_PoseStamped_decode_array(const void* buf, uint32_t offset, uint32_t maxlen, geometry_msgs_PoseStamped* p, uint32_t elements)
{
    uint32_t pos_byte = 0, element;
    int thislen;

    for (element = 0; element < elements; ++element) {

        /* header */
        thislen = __std_msgs_Header_decode_array(buf, offset + pos_byte, maxlen - pos_byte, &(p[element].header), 1);
        if (thislen < 0) return thislen; else pos_byte += thislen;

        /* pose */
        thislen = __geometry_msgs_Pose_decode_array(buf, offset + pos_byte, maxlen - pos_byte, &(p[element].pose), 1);
        if (thislen < 0) return thislen; else pos_byte += thislen;

    }
    return pos_byte;
}

int __geometry_msgs_PoseStamped_decode_array_cleanup(geometry_msgs_PoseStamped* p, uint32_t elements)
{
    uint32_t element;
    for (element = 0; element < elements; ++element) {

        __std_msgs_Header_decode_array_cleanup(&(p[element].header), 1);

        __geometry_msgs_Pose_decode_array_cleanup(&(p[element].pose), 1);

    }
    return 0;
}

int geometry_msgs_PoseStamped_decode(const void* buf, uint32_t offset, uint32_t maxlen, geometry_msgs_PoseStamped* p)
{
    uint32_t pos = 0;
    int thislen;
    int64_t hash = __geometry_msgs_PoseStamped_get_hash();

    int64_t this_hash;
    thislen = __int64_t_decode_array(buf, offset + pos, maxlen - pos, &this_hash, 1);
    if (thislen < 0) return thislen; else pos += thislen;
    if (this_hash != hash) return -1;

    thislen = __geometry_msgs_PoseStamped_decode_array(buf, offset + pos, maxlen - pos, p, 1);
    if (thislen < 0) return thislen; else pos += thislen;

    return pos;
}

int geometry_msgs_PoseStamped_decode_cleanup(geometry_msgs_PoseStamped* p)
{
    return __geometry_msgs_PoseStamped_decode_array_cleanup(p, 1);
}

uint32_t __geometry_msgs_PoseStamped_clone_array(const geometry_msgs_PoseStamped* p, geometry_msgs_PoseStamped* q, uint32_t elements)
{
    uint32_t n = 0, element;
    for (element = 0; element < elements; ++element) {

        n += __std_msgs_Header_clone_array(&(p[element].header), &(q[element].header), 1);

        n += __geometry_msgs_Pose_clone_array(&(p[element].pose), &(q[element].pose), 1);

    }
    return n;
}

geometry_msgs_PoseStamped* geometry_msgs_PoseStamped_copy(const geometry_msgs_PoseStamped* p)
{
    geometry_msgs_PoseStamped* q = (geometry_msgs_PoseStamped*) malloc(sizeof(geometry_msgs_PoseStamped));
    __geometry_msgs_PoseStamped_clone_array(p, q, 1);
    return q;
}

void geometry_msgs_PoseStamped_destroy(geometry_msgs_PoseStamped* p)
{
    __geometry_msgs_PoseStamped_decode_array_cleanup(p, 1);
    free(p);
}

int geometry_msgs_PoseStamped_publish(zcm_t* zcm, const char* channel, const geometry_msgs_PoseStamped* p)
{
      uint32_t max_data_size = geometry_msgs_PoseStamped_encoded_size (p);
      uint8_t* buf = (uint8_t*) malloc (max_data_size);
      if (!buf) return -1;
      int data_size = geometry_msgs_PoseStamped_encode (buf, 0, max_data_size, p);
      if (data_size < 0) {
          free (buf);
          return data_size;
      }
      int status = zcm_publish (zcm, channel, buf, (uint32_t)data_size);
      free (buf);
      return status;
}

struct _geometry_msgs_PoseStamped_subscription_t {
    geometry_msgs_PoseStamped_handler_t user_handler;
    void* userdata;
    zcm_sub_t* z_sub;
};
static
void geometry_msgs_PoseStamped_handler_stub (const zcm_recv_buf_t* rbuf,
                            const char* channel, void* userdata)
{
    int status;
    geometry_msgs_PoseStamped p;
    memset(&p, 0, sizeof(geometry_msgs_PoseStamped));
    status = geometry_msgs_PoseStamped_decode (rbuf->data, 0, rbuf->data_size, &p);
    if (status < 0) {
        #ifndef ZCM_EMBEDDED
        fprintf (stderr, "error %d decoding geometry_msgs_PoseStamped!!!\n", status);
        #endif
        return;
    }

    geometry_msgs_PoseStamped_subscription_t* h = (geometry_msgs_PoseStamped_subscription_t*) userdata;
    h->user_handler (rbuf, channel, &p, h->userdata);

    geometry_msgs_PoseStamped_decode_cleanup (&p);
}

geometry_msgs_PoseStamped_subscription_t* geometry_msgs_PoseStamped_subscribe (zcm_t* zcm,
                    const char* channel,
                    geometry_msgs_PoseStamped_handler_t f, void* userdata)
{
    geometry_msgs_PoseStamped_subscription_t* n = (geometry_msgs_PoseStamped_subscription_t*)
                       malloc(sizeof(geometry_msgs_PoseStamped_subscription_t));
    n->user_handler = f;
    n->userdata = userdata;
    n->z_sub = zcm_subscribe (zcm, channel,
                              geometry_msgs_PoseStamped_handler_stub, n);
    if (n->z_sub == NULL) {
        #ifndef ZCM_EMBEDDED
        fprintf (stderr,"couldn't reg geometry_msgs_PoseStamped ZCM handler!\n");
        #endif
        free (n);
        return NULL;
    }
    return n;
}

int geometry_msgs_PoseStamped_unsubscribe(zcm_t* zcm, geometry_msgs_PoseStamped_subscription_t* hid)
{
    int status = zcm_unsubscribe (zcm, hid->z_sub);
    if (0 != status) {
        #ifndef ZCM_EMBEDDED
        fprintf(stderr,
           "couldn't unsubscribe geometry_msgs_PoseStamped_handler %p!\n", hid);
        #endif
        return -1;
    }
    free (hid);
    return 0;
}

