"""ZCM type definitions
This file automatically generated by zcm.
DO NOT MODIFY BY HAND!!!!
"""

try:
    import cStringIO.StringIO as BytesIO
except ImportError:
    from io import BytesIO
import struct

from sensor_driver.common_lib.logging.message.geometry_msgs.Pose import Pose as geometry_msgs_Pose

from sensor_driver.common_lib.logging.message.std_msgs.Header import Header as std_msgs_Header

class PoseStamped(object):
    __slots__ = ["header", "pose"]

    IS_LITTLE_ENDIAN = False;
    def __init__(self):
        self.header = std_msgs_Header()
        self.pose = geometry_msgs_Pose()

    def encode(self):
        buf = BytesIO()
        buf.write(PoseStamped._get_packed_fingerprint())
        self._encode_one(buf)
        return buf.getvalue()

    def _encode_one(self, buf):
        assert self.header._get_packed_fingerprint() == std_msgs_Header._get_packed_fingerprint()
        self.header._encode_one(buf)
        assert self.pose._get_packed_fingerprint() == geometry_msgs_Pose._get_packed_fingerprint()
        self.pose._encode_one(buf)

    def decode(data):
        if hasattr(data, 'read'):
            buf = data
        else:
            buf = BytesIO(data)
        if buf.read(8) != PoseStamped._get_packed_fingerprint():
            raise ValueError("Decode error")
        return PoseStamped._decode_one(buf)
    decode = staticmethod(decode)

    def _decode_one(buf):
        self = PoseStamped()
        self.header = std_msgs_Header._decode_one(buf)
        self.pose = geometry_msgs_Pose._decode_one(buf)
        return self
    _decode_one = staticmethod(_decode_one)

    _hash = None
    def _get_hash_recursive(parents):
        if PoseStamped in parents: return 0
        newparents = parents + [PoseStamped]
        tmphash = (0xdeae7beebbb41387+ std_msgs_Header._get_hash_recursive(newparents)+ geometry_msgs_Pose._get_hash_recursive(newparents)) & 0xffffffffffffffff
        tmphash  = (((tmphash<<1)&0xffffffffffffffff)  + ((tmphash>>63)&0x1)) & 0xffffffffffffffff
        return tmphash
    _get_hash_recursive = staticmethod(_get_hash_recursive)
    _packed_fingerprint = None

    def _get_packed_fingerprint():
        if PoseStamped._packed_fingerprint is None:
            PoseStamped._packed_fingerprint = struct.pack(">Q", PoseStamped._get_hash_recursive([]))
        return PoseStamped._packed_fingerprint
    _get_packed_fingerprint = staticmethod(_get_packed_fingerprint)

