"""ZCM type definitions
This file automatically generated by zcm.
DO NOT MODIFY BY HAND!!!!
"""

try:
    import cStringIO.StringIO as BytesIO
except ImportError:
    from io import BytesIO
import struct

class Quaternion(object):
    __slots__ = ["x", "y", "z", "w"]

    IS_LITTLE_ENDIAN = False;
    def __init__(self):
        self.x = 0.0
        self.y = 0.0
        self.z = 0.0
        self.w = 0.0

    def encode(self):
        buf = BytesIO()
        buf.write(Quaternion._get_packed_fingerprint())
        self._encode_one(buf)
        return buf.getvalue()

    def _encode_one(self, buf):
        buf.write(struct.pack(">dddd", self.x, self.y, self.z, self.w))

    def decode(data):
        if hasattr(data, 'read'):
            buf = data
        else:
            buf = BytesIO(data)
        if buf.read(8) != Quaternion._get_packed_fingerprint():
            raise ValueError("Decode error")
        return Quaternion._decode_one(buf)
    decode = staticmethod(decode)

    def _decode_one(buf):
        self = Quaternion()
        self.x, self.y, self.z, self.w = struct.unpack(">dddd", buf.read(32))
        return self
    _decode_one = staticmethod(_decode_one)

    _hash = None
    def _get_hash_recursive(parents):
        if Quaternion in parents: return 0
        tmphash = (0x735cc017dc74b389) & 0xffffffffffffffff
        tmphash  = (((tmphash<<1)&0xffffffffffffffff)  + ((tmphash>>63)&0x1)) & 0xffffffffffffffff
        return tmphash
    _get_hash_recursive = staticmethod(_get_hash_recursive)
    _packed_fingerprint = None

    def _get_packed_fingerprint():
        if Quaternion._packed_fingerprint is None:
            Quaternion._packed_fingerprint = struct.pack(">Q", Quaternion._get_hash_recursive([]))
        return Quaternion._packed_fingerprint
    _get_packed_fingerprint = staticmethod(_get_packed_fingerprint)

