"""ZCM type definitions
This file automatically generated by zcm.
DO NOT MODIFY BY HAND!!!!
"""

try:
    import cStringIO.StringIO as BytesIO
except ImportError:
    from io import BytesIO
import struct

from sensor_driver.common_lib.logging.message.geometry_msgs.Twist import Twist as geometry_msgs_Twist

class TwistWithCovariance(object):
    __slots__ = ["twist", "covariance"]

    IS_LITTLE_ENDIAN = False;
    def __init__(self):
        self.twist = geometry_msgs_Twist()
        self.covariance = [ 0.0 for dim0 in range(36) ]

    def encode(self):
        buf = BytesIO()
        buf.write(TwistWithCovariance._get_packed_fingerprint())
        self._encode_one(buf)
        return buf.getvalue()

    def _encode_one(self, buf):
        assert self.twist._get_packed_fingerprint() == geometry_msgs_Twist._get_packed_fingerprint()
        self.twist._encode_one(buf)
        buf.write(struct.pack('>36d', *self.covariance[:36]))

    def decode(data):
        if hasattr(data, 'read'):
            buf = data
        else:
            buf = BytesIO(data)
        if buf.read(8) != TwistWithCovariance._get_packed_fingerprint():
            raise ValueError("Decode error")
        return TwistWithCovariance._decode_one(buf)
    decode = staticmethod(decode)

    def _decode_one(buf):
        self = TwistWithCovariance()
        self.twist = geometry_msgs_Twist._decode_one(buf)
        self.covariance = struct.unpack('>36d', buf.read(288))
        return self
    _decode_one = staticmethod(_decode_one)

    _hash = None
    def _get_hash_recursive(parents):
        if TwistWithCovariance in parents: return 0
        newparents = parents + [TwistWithCovariance]
        tmphash = (0xf9046e6876907ca6+ geometry_msgs_Twist._get_hash_recursive(newparents)) & 0xffffffffffffffff
        tmphash  = (((tmphash<<1)&0xffffffffffffffff)  + ((tmphash>>63)&0x1)) & 0xffffffffffffffff
        return tmphash
    _get_hash_recursive = staticmethod(_get_hash_recursive)
    _packed_fingerprint = None

    def _get_packed_fingerprint():
        if TwistWithCovariance._packed_fingerprint is None:
            TwistWithCovariance._packed_fingerprint = struct.pack(">Q", TwistWithCovariance._get_hash_recursive([]))
        return TwistWithCovariance._packed_fingerprint
    _get_packed_fingerprint = staticmethod(_get_packed_fingerprint)

