"""ZCM type definitions
This file automatically generated by zcm.
DO NOT MODIFY BY HAND!!!!
"""

try:
    import cStringIO.StringIO as BytesIO
except ImportError:
    from io import BytesIO
import struct

from sensor_driver.common_lib.logging.message.geometry_msgs.Vector3 import Vector3 as geometry_msgs_Vector3

class Twist(object):
    __slots__ = ["linear", "angular"]

    IS_LITTLE_ENDIAN = False;
    def __init__(self):
        self.linear = geometry_msgs_Vector3()
        self.angular = geometry_msgs_Vector3()

    def encode(self):
        buf = BytesIO()
        buf.write(Twist._get_packed_fingerprint())
        self._encode_one(buf)
        return buf.getvalue()

    def _encode_one(self, buf):
        assert self.linear._get_packed_fingerprint() == geometry_msgs_Vector3._get_packed_fingerprint()
        self.linear._encode_one(buf)
        assert self.angular._get_packed_fingerprint() == geometry_msgs_Vector3._get_packed_fingerprint()
        self.angular._encode_one(buf)

    def decode(data):
        if hasattr(data, 'read'):
            buf = data
        else:
            buf = BytesIO(data)
        if buf.read(8) != Twist._get_packed_fingerprint():
            raise ValueError("Decode error")
        return Twist._decode_one(buf)
    decode = staticmethod(decode)

    def _decode_one(buf):
        self = Twist()
        self.linear = geometry_msgs_Vector3._decode_one(buf)
        self.angular = geometry_msgs_Vector3._decode_one(buf)
        return self
    _decode_one = staticmethod(_decode_one)

    _hash = None
    def _get_hash_recursive(parents):
        if Twist in parents: return 0
        newparents = parents + [Twist]
        tmphash = (0x554776997dcacf0+ geometry_msgs_Vector3._get_hash_recursive(newparents)+ geometry_msgs_Vector3._get_hash_recursive(newparents)) & 0xffffffffffffffff
        tmphash  = (((tmphash<<1)&0xffffffffffffffff)  + ((tmphash>>63)&0x1)) & 0xffffffffffffffff
        return tmphash
    _get_hash_recursive = staticmethod(_get_hash_recursive)
    _packed_fingerprint = None

    def _get_packed_fingerprint():
        if Twist._packed_fingerprint is None:
            Twist._packed_fingerprint = struct.pack(">Q", Twist._get_hash_recursive([]))
        return Twist._packed_fingerprint
    _get_packed_fingerprint = staticmethod(_get_packed_fingerprint)

