// THIS IS AN AUTOMATICALLY GENERATED FILE.
// DO NOT MODIFY BY HAND!!
//
// Generated by zcm-gen

#include <string.h>
#ifndef ZCM_EMBEDDED
#include <stdio.h>
#endif
#include "std_msgs/std_msgs_Float.h"

static int __std_msgs_Float_hash_computed = 0;
static uint64_t __std_msgs_Float_hash;

uint64_t __std_msgs_Float_hash_recursive(const __zcm_hash_ptr* p)
{
    const __zcm_hash_ptr* fp;
    for (fp = p; fp != NULL; fp = fp->parent)
        if (fp->v == __std_msgs_Float_get_hash)
            return 0;

    __zcm_hash_ptr cp;
    cp.parent =  p;
    cp.v = (void*)__std_msgs_Float_get_hash;
    (void) cp;

    uint64_t hash = (uint64_t)0x4cab85fdc4b47046LL
         + __double_hash_recursive(&cp)
        ;

    return (hash<<1) + ((hash>>63)&1);
}

int64_t __std_msgs_Float_get_hash(void)
{
    if (!__std_msgs_Float_hash_computed) {
        __std_msgs_Float_hash = (int64_t)__std_msgs_Float_hash_recursive(NULL);
        __std_msgs_Float_hash_computed = 1;
    }

    return __std_msgs_Float_hash;
}

int __std_msgs_Float_encode_array(void* buf, uint32_t offset, uint32_t maxlen, const std_msgs_Float* p, uint32_t elements)
{
    uint32_t pos_byte = 0, element;
    int thislen;

    for (element = 0; element < elements; ++element) {

        /* data */
        thislen = __double_encode_array(buf, offset + pos_byte, maxlen - pos_byte, &(p[element].data), 1);
        if (thislen < 0) return thislen; else pos_byte += thislen;

    }
    return pos_byte;
}

int std_msgs_Float_encode(void* buf, uint32_t offset, uint32_t maxlen, const std_msgs_Float* p)
{
    uint32_t pos = 0;
    int thislen;
    int64_t hash = __std_msgs_Float_get_hash();

    thislen = __int64_t_encode_array(buf, offset + pos, maxlen - pos, &hash, 1);
    if (thislen < 0) return thislen; else pos += thislen;

    thislen = __std_msgs_Float_encode_array(buf, offset + pos, maxlen - pos, p, 1);
    if (thislen < 0) return thislen; else pos += thislen;

    return pos;
}

uint32_t __std_msgs_Float_encoded_array_size(const std_msgs_Float* p, uint32_t elements)
{
    uint32_t size = 0, element;
    for (element = 0; element < elements; ++element) {

        size += __double_encoded_array_size(&(p[element].data), 1); // data

    }
    return size;
}

uint32_t std_msgs_Float_encoded_size(const std_msgs_Float* p)
{
    return 8 + __std_msgs_Float_encoded_array_size(p, 1);
}

uint32_t std_msgs_Float_struct_size(void)
{
    return sizeof(std_msgs_Float);
}

uint32_t std_msgs_Float_num_fields(void)
{
    return 1;
}

int std_msgs_Float_get_field(const std_msgs_Float* p, uint32_t i, zcm_field_t* f)
{
    if (i >= std_msgs_Float_num_fields())
        return 1;
    
    switch (i) {
    
        case 0: {
            f->name = "data";
            f->type = ZCM_FIELD_DOUBLE;
            f->typestr = "double";
            f->num_dim = 0;
            f->data = (void*) &p->data;
            return 0;
        }
        
        default:
            return 1;
    }
}

const zcm_type_info_t* std_msgs_Float_get_type_info(void)
{
    static int init = 0;
    static zcm_type_info_t typeinfo;
    if (!init) {
        typeinfo.encode         = (zcm_encode_t) std_msgs_Float_encode;
        typeinfo.decode         = (zcm_decode_t) std_msgs_Float_decode;
        typeinfo.decode_cleanup = (zcm_decode_cleanup_t) std_msgs_Float_decode_cleanup;
        typeinfo.encoded_size   = (zcm_encoded_size_t) std_msgs_Float_encoded_size;
        typeinfo.struct_size    = (zcm_struct_size_t)  std_msgs_Float_struct_size;
        typeinfo.num_fields     = (zcm_num_fields_t) std_msgs_Float_num_fields;
        typeinfo.get_field      = (zcm_get_field_t) std_msgs_Float_get_field;
        typeinfo.get_hash       = (zcm_get_hash_t) __std_msgs_Float_get_hash;
    }
    
    return &typeinfo;
}

int __std_msgs_Float_decode_array(const void* buf, uint32_t offset, uint32_t maxlen, std_msgs_Float* p, uint32_t elements)
{
    uint32_t pos_byte = 0, element;
    int thislen;

    for (element = 0; element < elements; ++element) {

        /* data */
        thislen = __double_decode_array(buf, offset + pos_byte, maxlen - pos_byte, &(p[element].data), 1);
        if (thislen < 0) return thislen; else pos_byte += thislen;

    }
    return pos_byte;
}

int __std_msgs_Float_decode_array_cleanup(std_msgs_Float* p, uint32_t elements)
{
    uint32_t element;
    for (element = 0; element < elements; ++element) {

        __double_decode_array_cleanup(&(p[element].data), 1);

    }
    return 0;
}

int std_msgs_Float_decode(const void* buf, uint32_t offset, uint32_t maxlen, std_msgs_Float* p)
{
    uint32_t pos = 0;
    int thislen;
    int64_t hash = __std_msgs_Float_get_hash();

    int64_t this_hash;
    thislen = __int64_t_decode_array(buf, offset + pos, maxlen - pos, &this_hash, 1);
    if (thislen < 0) return thislen; else pos += thislen;
    if (this_hash != hash) return -1;

    thislen = __std_msgs_Float_decode_array(buf, offset + pos, maxlen - pos, p, 1);
    if (thislen < 0) return thislen; else pos += thislen;

    return pos;
}

int std_msgs_Float_decode_cleanup(std_msgs_Float* p)
{
    return __std_msgs_Float_decode_array_cleanup(p, 1);
}

uint32_t __std_msgs_Float_clone_array(const std_msgs_Float* p, std_msgs_Float* q, uint32_t elements)
{
    uint32_t n = 0, element;
    for (element = 0; element < elements; ++element) {

        n += __double_clone_array(&(p[element].data), &(q[element].data), 1);

    }
    return n;
}

std_msgs_Float* std_msgs_Float_copy(const std_msgs_Float* p)
{
    std_msgs_Float* q = (std_msgs_Float*) malloc(sizeof(std_msgs_Float));
    __std_msgs_Float_clone_array(p, q, 1);
    return q;
}

void std_msgs_Float_destroy(std_msgs_Float* p)
{
    __std_msgs_Float_decode_array_cleanup(p, 1);
    free(p);
}

int std_msgs_Float_publish(zcm_t* zcm, const char* channel, const std_msgs_Float* p)
{
      uint32_t max_data_size = std_msgs_Float_encoded_size (p);
      uint8_t* buf = (uint8_t*) malloc (max_data_size);
      if (!buf) return -1;
      int data_size = std_msgs_Float_encode (buf, 0, max_data_size, p);
      if (data_size < 0) {
          free (buf);
          return data_size;
      }
      int status = zcm_publish (zcm, channel, buf, (uint32_t)data_size);
      free (buf);
      return status;
}

struct _std_msgs_Float_subscription_t {
    std_msgs_Float_handler_t user_handler;
    void* userdata;
    zcm_sub_t* z_sub;
};
static
void std_msgs_Float_handler_stub (const zcm_recv_buf_t* rbuf,
                            const char* channel, void* userdata)
{
    int status;
    std_msgs_Float p;
    memset(&p, 0, sizeof(std_msgs_Float));
    status = std_msgs_Float_decode (rbuf->data, 0, rbuf->data_size, &p);
    if (status < 0) {
        #ifndef ZCM_EMBEDDED
        fprintf (stderr, "error %d decoding std_msgs_Float!!!\n", status);
        #endif
        return;
    }

    std_msgs_Float_subscription_t* h = (std_msgs_Float_subscription_t*) userdata;
    h->user_handler (rbuf, channel, &p, h->userdata);

    std_msgs_Float_decode_cleanup (&p);
}

std_msgs_Float_subscription_t* std_msgs_Float_subscribe (zcm_t* zcm,
                    const char* channel,
                    std_msgs_Float_handler_t f, void* userdata)
{
    std_msgs_Float_subscription_t* n = (std_msgs_Float_subscription_t*)
                       malloc(sizeof(std_msgs_Float_subscription_t));
    n->user_handler = f;
    n->userdata = userdata;
    n->z_sub = zcm_subscribe (zcm, channel,
                              std_msgs_Float_handler_stub, n);
    if (n->z_sub == NULL) {
        #ifndef ZCM_EMBEDDED
        fprintf (stderr,"couldn't reg std_msgs_Float ZCM handler!\n");
        #endif
        free (n);
        return NULL;
    }
    return n;
}

int std_msgs_Float_unsubscribe(zcm_t* zcm, std_msgs_Float_subscription_t* hid)
{
    int status = zcm_unsubscribe (zcm, hid->z_sub);
    if (0 != status) {
        #ifndef ZCM_EMBEDDED
        fprintf(stderr,
           "couldn't unsubscribe std_msgs_Float_handler %p!\n", hid);
        #endif
        return -1;
    }
    free (hid);
    return 0;
}

