# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: internal.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='internal.proto',
  package='',
  syntax='proto2',
  serialized_options=None,
  serialized_pb=_b('\n\x0einternal.proto\"Q\n\x0fLidarPointcloud\x12\x12\n\nlidar_name\x18\x01 \x01(\t\x12\x0e\n\x06points\x18\x02 \x01(\x0c\x12\x0c\n\x04\x61ttr\x18\x03 \x01(\x0c\x12\x0c\n\x04type\x18\x04 \x01(\t\"6\n\x10\x43\x61meraImageBytes\x12\x13\n\x0b\x63\x61mera_name\x18\x01 \x01(\t\x12\r\n\x05image\x18\x02 \x01(\x0c\"T\n\x12LidarPointcloudMap\x12\x1c\n\x02lp\x18\x01 \x03(\x0b\x32\x10.LidarPointcloud\x12 \n\x05image\x18\x02 \x03(\x0b\x32\x11.CameraImageBytes')
)




_LIDARPOINTCLOUD = _descriptor.Descriptor(
  name='LidarPointcloud',
  full_name='LidarPointcloud',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='lidar_name', full_name='LidarPointcloud.lidar_name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='points', full_name='LidarPointcloud.points', index=1,
      number=2, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='attr', full_name='LidarPointcloud.attr', index=2,
      number=3, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='type', full_name='LidarPointcloud.type', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=18,
  serialized_end=99,
)


_CAMERAIMAGEBYTES = _descriptor.Descriptor(
  name='CameraImageBytes',
  full_name='CameraImageBytes',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='camera_name', full_name='CameraImageBytes.camera_name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='image', full_name='CameraImageBytes.image', index=1,
      number=2, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=101,
  serialized_end=155,
)


_LIDARPOINTCLOUDMAP = _descriptor.Descriptor(
  name='LidarPointcloudMap',
  full_name='LidarPointcloudMap',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='lp', full_name='LidarPointcloudMap.lp', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='image', full_name='LidarPointcloudMap.image', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=157,
  serialized_end=241,
)

_LIDARPOINTCLOUDMAP.fields_by_name['lp'].message_type = _LIDARPOINTCLOUD
_LIDARPOINTCLOUDMAP.fields_by_name['image'].message_type = _CAMERAIMAGEBYTES
DESCRIPTOR.message_types_by_name['LidarPointcloud'] = _LIDARPOINTCLOUD
DESCRIPTOR.message_types_by_name['CameraImageBytes'] = _CAMERAIMAGEBYTES
DESCRIPTOR.message_types_by_name['LidarPointcloudMap'] = _LIDARPOINTCLOUDMAP
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

LidarPointcloud = _reflection.GeneratedProtocolMessageType('LidarPointcloud', (_message.Message,), {
  'DESCRIPTOR' : _LIDARPOINTCLOUD,
  '__module__' : 'internal_pb2'
  # @@protoc_insertion_point(class_scope:LidarPointcloud)
  })
_sym_db.RegisterMessage(LidarPointcloud)

CameraImageBytes = _reflection.GeneratedProtocolMessageType('CameraImageBytes', (_message.Message,), {
  'DESCRIPTOR' : _CAMERAIMAGEBYTES,
  '__module__' : 'internal_pb2'
  # @@protoc_insertion_point(class_scope:CameraImageBytes)
  })
_sym_db.RegisterMessage(CameraImageBytes)

LidarPointcloudMap = _reflection.GeneratedProtocolMessageType('LidarPointcloudMap', (_message.Message,), {
  'DESCRIPTOR' : _LIDARPOINTCLOUDMAP,
  '__module__' : 'internal_pb2'
  # @@protoc_insertion_point(class_scope:LidarPointcloudMap)
  })
_sym_db.RegisterMessage(LidarPointcloudMap)


# @@protoc_insertion_point(module_scope)
