// THIS IS AN AUTOMATICALLY GENERATED FILE.
// DO NOT MODIFY BY HAND!!
//
// Generated by zcm-gen

#include <stdint.h>
#include <stdlib.h>
#include <zcm/zcm_coretypes.h>
#include <zcm/zcm.h>

#ifndef _nav_msgs_Odometry_h
#define _nav_msgs_Odometry_h

#ifdef __cplusplus
extern "C" {
#endif

#include "std_msgs/std_msgs_Header.h"
#include "geometry_msgs/geometry_msgs_PoseWithCovariance.h"
#include "geometry_msgs/geometry_msgs_TwistWithCovariance.h"
#define NAV_MSGS_ODOMETRY_IS_LITTLE_ENDIAN 0
typedef struct _nav_msgs_Odometry nav_msgs_Odometry;
struct _nav_msgs_Odometry
{
    std_msgs_Header header;
    char*      child_frame_id;
    geometry_msgs_PoseWithCovariance pose;
    geometry_msgs_TwistWithCovariance twist;
};

/**
 * Create a deep copy of a nav_msgs_Odometry.
 * When no longer needed, destroy it with nav_msgs_Odometry_destroy()
 */
nav_msgs_Odometry* nav_msgs_Odometry_copy(const nav_msgs_Odometry* to_copy);

/**
 * Destroy an instance of nav_msgs_Odometry created by nav_msgs_Odometry_copy()
 */
void nav_msgs_Odometry_destroy(nav_msgs_Odometry* to_destroy);

/**
 * Identifies a single subscription.  This is an opaque data type.
 */
typedef struct _nav_msgs_Odometry_subscription_t nav_msgs_Odometry_subscription_t;

/**
 * Prototype for a callback function invoked when a message of type
 * nav_msgs_Odometry is received.
 */
typedef void(*nav_msgs_Odometry_handler_t)(const zcm_recv_buf_t* rbuf,
             const char* channel, const nav_msgs_Odometry* msg, void* userdata);

/**
 * Publish a message of type nav_msgs_Odometry using ZCM.
 *
 * @param zcm The ZCM instance to publish with.
 * @param channel The channel to publish on.
 * @param msg The message to publish.
 * @return 0 on success, <0 on error.  Success means ZCM has transferred
 * responsibility of the message data to the OS.
 */
int nav_msgs_Odometry_publish(zcm_t* zcm, const char* channel, const nav_msgs_Odometry* msg);

/**
 * Subscribe to messages of type nav_msgs_Odometry using ZCM.
 *
 * @param zcm The ZCM instance to subscribe with.
 * @param channel The channel to subscribe to.
 * @param handler The callback function invoked by ZCM when a message is received.
 *                This function is invoked by ZCM during calls to zcm_handle() and
 *                zcm_handle_timeout().
 * @param userdata An opaque pointer passed to @p handler when it is invoked.
 * @return pointer to subscription type, NULL if failure. Must clean up
 *         dynamic memory by passing the pointer to nav_msgs_Odometry_unsubscribe.
 */
nav_msgs_Odometry_subscription_t* nav_msgs_Odometry_subscribe(zcm_t* zcm, const char* channel, nav_msgs_Odometry_handler_t handler, void* userdata);

/**
 * Removes and destroys a subscription created by nav_msgs_Odometry_subscribe()
 */
int nav_msgs_Odometry_unsubscribe(zcm_t* zcm, nav_msgs_Odometry_subscription_t* hid);
/**
 * Encode a message of type nav_msgs_Odometry into binary form.
 *
 * @param buf The output buffer.
 * @param offset Encoding starts at this byte offset into @p buf.
 * @param maxlen Maximum number of bytes to write.  This should generally
 *               be equal to nav_msgs_Odometry_encoded_size().
 * @param msg The message to encode.
 * @return The number of bytes encoded, or <0 if an error occured.
 */
int nav_msgs_Odometry_encode(void* buf, uint32_t offset, uint32_t maxlen, const nav_msgs_Odometry* p);

/**
 * Decode a message of type nav_msgs_Odometry from binary form.
 * When decoding messages containing strings or variable-length arrays, this
 * function may allocate memory.  When finished with the decoded message,
 * release allocated resources with nav_msgs_Odometry_decode_cleanup().
 *
 * @param buf The buffer containing the encoded message
 * @param offset The byte offset into @p buf where the encoded message starts.
 * @param maxlen The maximum number of bytes to read while decoding.
 * @param msg Output parameter where the decoded message is stored
 * @return The number of bytes decoded, or <0 if an error occured.
 */
int nav_msgs_Odometry_decode(const void* buf, uint32_t offset, uint32_t maxlen, nav_msgs_Odometry* msg);

/**
 * Release resources allocated by nav_msgs_Odometry_decode()
 * @return 0
 */
int nav_msgs_Odometry_decode_cleanup(nav_msgs_Odometry* p);

/**
 * Check how many bytes are required to encode a message of type nav_msgs_Odometry
 */
uint32_t nav_msgs_Odometry_encoded_size(const nav_msgs_Odometry* p);
uint32_t nav_msgs_Odometry_struct_size(void);
uint32_t nav_msgs_Odometry_num_fields(void);
int      nav_msgs_Odometry_get_field(const nav_msgs_Odometry* p, uint32_t i, zcm_field_t* f);
const zcm_type_info_t* nav_msgs_Odometry_get_type_info(void);

// ZCM support functions. Users should not call these
int64_t  __nav_msgs_Odometry_get_hash(void);
uint64_t __nav_msgs_Odometry_hash_recursive(const __zcm_hash_ptr* p);
int      __nav_msgs_Odometry_encode_array(void* buf, uint32_t offset, uint32_t maxlen, const nav_msgs_Odometry* p, uint32_t elements);
int      __nav_msgs_Odometry_decode_array(const void* buf, uint32_t offset, uint32_t maxlen, nav_msgs_Odometry* p, uint32_t elements);
int      __nav_msgs_Odometry_decode_array_cleanup(nav_msgs_Odometry* p, uint32_t elements);
uint32_t __nav_msgs_Odometry_encoded_array_size(const nav_msgs_Odometry* p, uint32_t elements);
uint32_t __nav_msgs_Odometry_clone_array(const nav_msgs_Odometry* p, nav_msgs_Odometry* q, uint32_t elements);

#ifdef __cplusplus
}
#endif

#endif
