// THIS IS AN AUTOMATICALLY GENERATED FILE.
// DO NOT MODIFY BY HAND!!
//
// Generated by zcm-gen

#include <string.h>
#ifndef ZCM_EMBEDDED
#include <stdio.h>
#endif
#include "nav_msgs/nav_msgs_Odometry.h"

static int __nav_msgs_Odometry_hash_computed = 0;
static uint64_t __nav_msgs_Odometry_hash;

uint64_t __nav_msgs_Odometry_hash_recursive(const __zcm_hash_ptr* p)
{
    const __zcm_hash_ptr* fp;
    for (fp = p; fp != NULL; fp = fp->parent)
        if (fp->v == __nav_msgs_Odometry_get_hash)
            return 0;

    __zcm_hash_ptr cp;
    cp.parent =  p;
    cp.v = (void*)__nav_msgs_Odometry_get_hash;
    (void) cp;

    uint64_t hash = (uint64_t)0x682b2733853d9e5bLL
         + __std_msgs_Header_hash_recursive(&cp)
         + __string_hash_recursive(&cp)
         + __geometry_msgs_PoseWithCovariance_hash_recursive(&cp)
         + __geometry_msgs_TwistWithCovariance_hash_recursive(&cp)
        ;

    return (hash<<1) + ((hash>>63)&1);
}

int64_t __nav_msgs_Odometry_get_hash(void)
{
    if (!__nav_msgs_Odometry_hash_computed) {
        __nav_msgs_Odometry_hash = (int64_t)__nav_msgs_Odometry_hash_recursive(NULL);
        __nav_msgs_Odometry_hash_computed = 1;
    }

    return __nav_msgs_Odometry_hash;
}

int __nav_msgs_Odometry_encode_array(void* buf, uint32_t offset, uint32_t maxlen, const nav_msgs_Odometry* p, uint32_t elements)
{
    uint32_t pos_byte = 0, element;
    int thislen;

    for (element = 0; element < elements; ++element) {

        /* header */
        thislen = __std_msgs_Header_encode_array(buf, offset + pos_byte, maxlen - pos_byte, &(p[element].header), 1);
        if (thislen < 0) return thislen; else pos_byte += thislen;

        /* child_frame_id */
        thislen = __string_encode_array(buf, offset + pos_byte, maxlen - pos_byte, &(p[element].child_frame_id), 1);
        if (thislen < 0) return thislen; else pos_byte += thislen;

        /* pose */
        thislen = __geometry_msgs_PoseWithCovariance_encode_array(buf, offset + pos_byte, maxlen - pos_byte, &(p[element].pose), 1);
        if (thislen < 0) return thislen; else pos_byte += thislen;

        /* twist */
        thislen = __geometry_msgs_TwistWithCovariance_encode_array(buf, offset + pos_byte, maxlen - pos_byte, &(p[element].twist), 1);
        if (thislen < 0) return thislen; else pos_byte += thislen;

    }
    return pos_byte;
}

int nav_msgs_Odometry_encode(void* buf, uint32_t offset, uint32_t maxlen, const nav_msgs_Odometry* p)
{
    uint32_t pos = 0;
    int thislen;
    int64_t hash = __nav_msgs_Odometry_get_hash();

    thislen = __int64_t_encode_array(buf, offset + pos, maxlen - pos, &hash, 1);
    if (thislen < 0) return thislen; else pos += thislen;

    thislen = __nav_msgs_Odometry_encode_array(buf, offset + pos, maxlen - pos, p, 1);
    if (thislen < 0) return thislen; else pos += thislen;

    return pos;
}

uint32_t __nav_msgs_Odometry_encoded_array_size(const nav_msgs_Odometry* p, uint32_t elements)
{
    uint32_t size = 0, element;
    for (element = 0; element < elements; ++element) {

        size += __std_msgs_Header_encoded_array_size(&(p[element].header), 1); // header

        size += __string_encoded_array_size(&(p[element].child_frame_id), 1); // child_frame_id

        size += __geometry_msgs_PoseWithCovariance_encoded_array_size(&(p[element].pose), 1); // pose

        size += __geometry_msgs_TwistWithCovariance_encoded_array_size(&(p[element].twist), 1); // twist

    }
    return size;
}

uint32_t nav_msgs_Odometry_encoded_size(const nav_msgs_Odometry* p)
{
    return 8 + __nav_msgs_Odometry_encoded_array_size(p, 1);
}

uint32_t nav_msgs_Odometry_struct_size(void)
{
    return sizeof(nav_msgs_Odometry);
}

uint32_t nav_msgs_Odometry_num_fields(void)
{
    return 4;
}

int nav_msgs_Odometry_get_field(const nav_msgs_Odometry* p, uint32_t i, zcm_field_t* f)
{
    if (i >= nav_msgs_Odometry_num_fields())
        return 1;
    
    switch (i) {
    
        case 0: {
            /* Header */
            f->name = "header";
            f->type = ZCM_FIELD_USER_TYPE;
            f->typestr = "std_msgs.Header";
            f->num_dim = 0;
            f->data = (void*) &p->header;
            return 0;
        }
        
        case 1: {
            f->name = "child_frame_id";
            f->type = ZCM_FIELD_STRING;
            f->typestr = "string";
            f->num_dim = 0;
            f->data = (void*) &p->child_frame_id;
            return 0;
        }
        
        case 2: {
            /* PoseWithCovariance */
            f->name = "pose";
            f->type = ZCM_FIELD_USER_TYPE;
            f->typestr = "geometry_msgs.PoseWithCovariance";
            f->num_dim = 0;
            f->data = (void*) &p->pose;
            return 0;
        }
        
        case 3: {
            /* TwistWithCovariance */
            f->name = "twist";
            f->type = ZCM_FIELD_USER_TYPE;
            f->typestr = "geometry_msgs.TwistWithCovariance";
            f->num_dim = 0;
            f->data = (void*) &p->twist;
            return 0;
        }
        
        default:
            return 1;
    }
}

const zcm_type_info_t* nav_msgs_Odometry_get_type_info(void)
{
    static int init = 0;
    static zcm_type_info_t typeinfo;
    if (!init) {
        typeinfo.encode         = (zcm_encode_t) nav_msgs_Odometry_encode;
        typeinfo.decode         = (zcm_decode_t) nav_msgs_Odometry_decode;
        typeinfo.decode_cleanup = (zcm_decode_cleanup_t) nav_msgs_Odometry_decode_cleanup;
        typeinfo.encoded_size   = (zcm_encoded_size_t) nav_msgs_Odometry_encoded_size;
        typeinfo.struct_size    = (zcm_struct_size_t)  nav_msgs_Odometry_struct_size;
        typeinfo.num_fields     = (zcm_num_fields_t) nav_msgs_Odometry_num_fields;
        typeinfo.get_field      = (zcm_get_field_t) nav_msgs_Odometry_get_field;
        typeinfo.get_hash       = (zcm_get_hash_t) __nav_msgs_Odometry_get_hash;
    }
    
    return &typeinfo;
}

int __nav_msgs_Odometry_decode_array(const void* buf, uint32_t offset, uint32_t maxlen, nav_msgs_Odometry* p, uint32_t elements)
{
    uint32_t pos_byte = 0, element;
    int thislen;

    for (element = 0; element < elements; ++element) {

        /* header */
        thislen = __std_msgs_Header_decode_array(buf, offset + pos_byte, maxlen - pos_byte, &(p[element].header), 1);
        if (thislen < 0) return thislen; else pos_byte += thislen;

        /* child_frame_id */
        thislen = __string_decode_array(buf, offset + pos_byte, maxlen - pos_byte, &(p[element].child_frame_id), 1);
        if (thislen < 0) return thislen; else pos_byte += thislen;

        /* pose */
        thislen = __geometry_msgs_PoseWithCovariance_decode_array(buf, offset + pos_byte, maxlen - pos_byte, &(p[element].pose), 1);
        if (thislen < 0) return thislen; else pos_byte += thislen;

        /* twist */
        thislen = __geometry_msgs_TwistWithCovariance_decode_array(buf, offset + pos_byte, maxlen - pos_byte, &(p[element].twist), 1);
        if (thislen < 0) return thislen; else pos_byte += thislen;

    }
    return pos_byte;
}

int __nav_msgs_Odometry_decode_array_cleanup(nav_msgs_Odometry* p, uint32_t elements)
{
    uint32_t element;
    for (element = 0; element < elements; ++element) {

        __std_msgs_Header_decode_array_cleanup(&(p[element].header), 1);

        __string_decode_array_cleanup(&(p[element].child_frame_id), 1);

        __geometry_msgs_PoseWithCovariance_decode_array_cleanup(&(p[element].pose), 1);

        __geometry_msgs_TwistWithCovariance_decode_array_cleanup(&(p[element].twist), 1);

    }
    return 0;
}

int nav_msgs_Odometry_decode(const void* buf, uint32_t offset, uint32_t maxlen, nav_msgs_Odometry* p)
{
    uint32_t pos = 0;
    int thislen;
    int64_t hash = __nav_msgs_Odometry_get_hash();

    int64_t this_hash;
    thislen = __int64_t_decode_array(buf, offset + pos, maxlen - pos, &this_hash, 1);
    if (thislen < 0) return thislen; else pos += thislen;
    if (this_hash != hash) return -1;

    thislen = __nav_msgs_Odometry_decode_array(buf, offset + pos, maxlen - pos, p, 1);
    if (thislen < 0) return thislen; else pos += thislen;

    return pos;
}

int nav_msgs_Odometry_decode_cleanup(nav_msgs_Odometry* p)
{
    return __nav_msgs_Odometry_decode_array_cleanup(p, 1);
}

uint32_t __nav_msgs_Odometry_clone_array(const nav_msgs_Odometry* p, nav_msgs_Odometry* q, uint32_t elements)
{
    uint32_t n = 0, element;
    for (element = 0; element < elements; ++element) {

        n += __std_msgs_Header_clone_array(&(p[element].header), &(q[element].header), 1);

        n += __string_clone_array(&(p[element].child_frame_id), &(q[element].child_frame_id), 1);

        n += __geometry_msgs_PoseWithCovariance_clone_array(&(p[element].pose), &(q[element].pose), 1);

        n += __geometry_msgs_TwistWithCovariance_clone_array(&(p[element].twist), &(q[element].twist), 1);

    }
    return n;
}

nav_msgs_Odometry* nav_msgs_Odometry_copy(const nav_msgs_Odometry* p)
{
    nav_msgs_Odometry* q = (nav_msgs_Odometry*) malloc(sizeof(nav_msgs_Odometry));
    __nav_msgs_Odometry_clone_array(p, q, 1);
    return q;
}

void nav_msgs_Odometry_destroy(nav_msgs_Odometry* p)
{
    __nav_msgs_Odometry_decode_array_cleanup(p, 1);
    free(p);
}

int nav_msgs_Odometry_publish(zcm_t* zcm, const char* channel, const nav_msgs_Odometry* p)
{
      uint32_t max_data_size = nav_msgs_Odometry_encoded_size (p);
      uint8_t* buf = (uint8_t*) malloc (max_data_size);
      if (!buf) return -1;
      int data_size = nav_msgs_Odometry_encode (buf, 0, max_data_size, p);
      if (data_size < 0) {
          free (buf);
          return data_size;
      }
      int status = zcm_publish (zcm, channel, buf, (uint32_t)data_size);
      free (buf);
      return status;
}

struct _nav_msgs_Odometry_subscription_t {
    nav_msgs_Odometry_handler_t user_handler;
    void* userdata;
    zcm_sub_t* z_sub;
};
static
void nav_msgs_Odometry_handler_stub (const zcm_recv_buf_t* rbuf,
                            const char* channel, void* userdata)
{
    int status;
    nav_msgs_Odometry p;
    memset(&p, 0, sizeof(nav_msgs_Odometry));
    status = nav_msgs_Odometry_decode (rbuf->data, 0, rbuf->data_size, &p);
    if (status < 0) {
        #ifndef ZCM_EMBEDDED
        fprintf (stderr, "error %d decoding nav_msgs_Odometry!!!\n", status);
        #endif
        return;
    }

    nav_msgs_Odometry_subscription_t* h = (nav_msgs_Odometry_subscription_t*) userdata;
    h->user_handler (rbuf, channel, &p, h->userdata);

    nav_msgs_Odometry_decode_cleanup (&p);
}

nav_msgs_Odometry_subscription_t* nav_msgs_Odometry_subscribe (zcm_t* zcm,
                    const char* channel,
                    nav_msgs_Odometry_handler_t f, void* userdata)
{
    nav_msgs_Odometry_subscription_t* n = (nav_msgs_Odometry_subscription_t*)
                       malloc(sizeof(nav_msgs_Odometry_subscription_t));
    n->user_handler = f;
    n->userdata = userdata;
    n->z_sub = zcm_subscribe (zcm, channel,
                              nav_msgs_Odometry_handler_stub, n);
    if (n->z_sub == NULL) {
        #ifndef ZCM_EMBEDDED
        fprintf (stderr,"couldn't reg nav_msgs_Odometry ZCM handler!\n");
        #endif
        free (n);
        return NULL;
    }
    return n;
}

int nav_msgs_Odometry_unsubscribe(zcm_t* zcm, nav_msgs_Odometry_subscription_t* hid)
{
    int status = zcm_unsubscribe (zcm, hid->z_sub);
    if (0 != status) {
        #ifndef ZCM_EMBEDDED
        fprintf(stderr,
           "couldn't unsubscribe nav_msgs_Odometry_handler %p!\n", hid);
        #endif
        return -1;
    }
    free (hid);
    return 0;
}

