// THIS IS AN AUTOMATICALLY GENERATED FILE.
// DO NOT MODIFY BY HAND!!
//
// Generated by zcm-gen

#include <stdint.h>
#include <stdlib.h>
#include <zcm/zcm_coretypes.h>
#include <zcm/zcm.h>

#ifndef _nav_msgs_Path_h
#define _nav_msgs_Path_h

#ifdef __cplusplus
extern "C" {
#endif

#include "std_msgs/std_msgs_Header.h"
#include "geometry_msgs/geometry_msgs_PoseStamped.h"
#define NAV_MSGS_PATH_IS_LITTLE_ENDIAN 0
typedef struct _nav_msgs_Path nav_msgs_Path;
struct _nav_msgs_Path
{
    std_msgs_Header header;
    int32_t    size;
    geometry_msgs_PoseStamped *poses;
};

/**
 * Create a deep copy of a nav_msgs_Path.
 * When no longer needed, destroy it with nav_msgs_Path_destroy()
 */
nav_msgs_Path* nav_msgs_Path_copy(const nav_msgs_Path* to_copy);

/**
 * Destroy an instance of nav_msgs_Path created by nav_msgs_Path_copy()
 */
void nav_msgs_Path_destroy(nav_msgs_Path* to_destroy);

/**
 * Identifies a single subscription.  This is an opaque data type.
 */
typedef struct _nav_msgs_Path_subscription_t nav_msgs_Path_subscription_t;

/**
 * Prototype for a callback function invoked when a message of type
 * nav_msgs_Path is received.
 */
typedef void(*nav_msgs_Path_handler_t)(const zcm_recv_buf_t* rbuf,
             const char* channel, const nav_msgs_Path* msg, void* userdata);

/**
 * Publish a message of type nav_msgs_Path using ZCM.
 *
 * @param zcm The ZCM instance to publish with.
 * @param channel The channel to publish on.
 * @param msg The message to publish.
 * @return 0 on success, <0 on error.  Success means ZCM has transferred
 * responsibility of the message data to the OS.
 */
int nav_msgs_Path_publish(zcm_t* zcm, const char* channel, const nav_msgs_Path* msg);

/**
 * Subscribe to messages of type nav_msgs_Path using ZCM.
 *
 * @param zcm The ZCM instance to subscribe with.
 * @param channel The channel to subscribe to.
 * @param handler The callback function invoked by ZCM when a message is received.
 *                This function is invoked by ZCM during calls to zcm_handle() and
 *                zcm_handle_timeout().
 * @param userdata An opaque pointer passed to @p handler when it is invoked.
 * @return pointer to subscription type, NULL if failure. Must clean up
 *         dynamic memory by passing the pointer to nav_msgs_Path_unsubscribe.
 */
nav_msgs_Path_subscription_t* nav_msgs_Path_subscribe(zcm_t* zcm, const char* channel, nav_msgs_Path_handler_t handler, void* userdata);

/**
 * Removes and destroys a subscription created by nav_msgs_Path_subscribe()
 */
int nav_msgs_Path_unsubscribe(zcm_t* zcm, nav_msgs_Path_subscription_t* hid);
/**
 * Encode a message of type nav_msgs_Path into binary form.
 *
 * @param buf The output buffer.
 * @param offset Encoding starts at this byte offset into @p buf.
 * @param maxlen Maximum number of bytes to write.  This should generally
 *               be equal to nav_msgs_Path_encoded_size().
 * @param msg The message to encode.
 * @return The number of bytes encoded, or <0 if an error occured.
 */
int nav_msgs_Path_encode(void* buf, uint32_t offset, uint32_t maxlen, const nav_msgs_Path* p);

/**
 * Decode a message of type nav_msgs_Path from binary form.
 * When decoding messages containing strings or variable-length arrays, this
 * function may allocate memory.  When finished with the decoded message,
 * release allocated resources with nav_msgs_Path_decode_cleanup().
 *
 * @param buf The buffer containing the encoded message
 * @param offset The byte offset into @p buf where the encoded message starts.
 * @param maxlen The maximum number of bytes to read while decoding.
 * @param msg Output parameter where the decoded message is stored
 * @return The number of bytes decoded, or <0 if an error occured.
 */
int nav_msgs_Path_decode(const void* buf, uint32_t offset, uint32_t maxlen, nav_msgs_Path* msg);

/**
 * Release resources allocated by nav_msgs_Path_decode()
 * @return 0
 */
int nav_msgs_Path_decode_cleanup(nav_msgs_Path* p);

/**
 * Check how many bytes are required to encode a message of type nav_msgs_Path
 */
uint32_t nav_msgs_Path_encoded_size(const nav_msgs_Path* p);
uint32_t nav_msgs_Path_struct_size(void);
uint32_t nav_msgs_Path_num_fields(void);
int      nav_msgs_Path_get_field(const nav_msgs_Path* p, uint32_t i, zcm_field_t* f);
const zcm_type_info_t* nav_msgs_Path_get_type_info(void);

// ZCM support functions. Users should not call these
int64_t  __nav_msgs_Path_get_hash(void);
uint64_t __nav_msgs_Path_hash_recursive(const __zcm_hash_ptr* p);
int      __nav_msgs_Path_encode_array(void* buf, uint32_t offset, uint32_t maxlen, const nav_msgs_Path* p, uint32_t elements);
int      __nav_msgs_Path_decode_array(const void* buf, uint32_t offset, uint32_t maxlen, nav_msgs_Path* p, uint32_t elements);
int      __nav_msgs_Path_decode_array_cleanup(nav_msgs_Path* p, uint32_t elements);
uint32_t __nav_msgs_Path_encoded_array_size(const nav_msgs_Path* p, uint32_t elements);
uint32_t __nav_msgs_Path_clone_array(const nav_msgs_Path* p, nav_msgs_Path* q, uint32_t elements);

#ifdef __cplusplus
}
#endif

#endif
