"""ZCM type definitions
This file automatically generated by zcm.
DO NOT MODIFY BY HAND!!!!
"""

try:
    import cStringIO.StringIO as BytesIO
except ImportError:
    from io import BytesIO
import struct

from sensor_driver.common_lib.logging.message.geometry_msgs.TwistWithCovariance import TwistWithCovariance as geometry_msgs_TwistWithCovariance

from sensor_driver.common_lib.logging.message.geometry_msgs.PoseWithCovariance import PoseWithCovariance as geometry_msgs_PoseWithCovariance

from sensor_driver.common_lib.logging.message.std_msgs.Header import Header as std_msgs_Header

class Odometry(object):
    __slots__ = ["header", "child_frame_id", "pose", "twist"]

    IS_LITTLE_ENDIAN = False;
    def __init__(self):
        self.header = std_msgs_Header()
        self.child_frame_id = ""
        self.pose = geometry_msgs_PoseWithCovariance()
        self.twist = geometry_msgs_TwistWithCovariance()

    def encode(self):
        buf = BytesIO()
        buf.write(Odometry._get_packed_fingerprint())
        self._encode_one(buf)
        return buf.getvalue()

    def _encode_one(self, buf):
        assert self.header._get_packed_fingerprint() == std_msgs_Header._get_packed_fingerprint()
        self.header._encode_one(buf)
        __child_frame_id_encoded = self.child_frame_id.encode('utf-8')
        buf.write(struct.pack('>I', len(__child_frame_id_encoded)+1))
        buf.write(__child_frame_id_encoded)
        buf.write(b"\0")
        assert self.pose._get_packed_fingerprint() == geometry_msgs_PoseWithCovariance._get_packed_fingerprint()
        self.pose._encode_one(buf)
        assert self.twist._get_packed_fingerprint() == geometry_msgs_TwistWithCovariance._get_packed_fingerprint()
        self.twist._encode_one(buf)

    def decode(data):
        if hasattr(data, 'read'):
            buf = data
        else:
            buf = BytesIO(data)
        if buf.read(8) != Odometry._get_packed_fingerprint():
            raise ValueError("Decode error")
        return Odometry._decode_one(buf)
    decode = staticmethod(decode)

    def _decode_one(buf):
        self = Odometry()
        self.header = std_msgs_Header._decode_one(buf)
        __child_frame_id_len = struct.unpack('>I', buf.read(4))[0]
        self.child_frame_id = buf.read(__child_frame_id_len)[:-1].decode('utf-8', 'replace')
        self.pose = geometry_msgs_PoseWithCovariance._decode_one(buf)
        self.twist = geometry_msgs_TwistWithCovariance._decode_one(buf)
        return self
    _decode_one = staticmethod(_decode_one)

    _hash = None
    def _get_hash_recursive(parents):
        if Odometry in parents: return 0
        newparents = parents + [Odometry]
        tmphash = (0x682b2733853d9e5b+ std_msgs_Header._get_hash_recursive(newparents)+ geometry_msgs_PoseWithCovariance._get_hash_recursive(newparents)+ geometry_msgs_TwistWithCovariance._get_hash_recursive(newparents)) & 0xffffffffffffffff
        tmphash  = (((tmphash<<1)&0xffffffffffffffff)  + ((tmphash>>63)&0x1)) & 0xffffffffffffffff
        return tmphash
    _get_hash_recursive = staticmethod(_get_hash_recursive)
    _packed_fingerprint = None

    def _get_packed_fingerprint():
        if Odometry._packed_fingerprint is None:
            Odometry._packed_fingerprint = struct.pack(">Q", Odometry._get_hash_recursive([]))
        return Odometry._packed_fingerprint
    _get_packed_fingerprint = staticmethod(_get_packed_fingerprint)

