"""ZCM type definitions
This file automatically generated by zcm.
DO NOT MODIFY BY HAND!!!!
"""

try:
    import cStringIO.StringIO as BytesIO
except ImportError:
    from io import BytesIO
import struct

from sensor_driver.common_lib.logging.message.std_msgs.Header import Header as std_msgs_Header

class CompressedImage(object):
    __slots__ = ["header", "format", "size", "data"]

    IS_LITTLE_ENDIAN = False;
    def __init__(self):
        self.header = std_msgs_Header()
        self.format = ""
        self.size = 0
        self.data = bytearray()

    def encode(self):
        buf = BytesIO()
        buf.write(CompressedImage._get_packed_fingerprint())
        self._encode_one(buf)
        return buf.getvalue()

    def _encode_one(self, buf):
        assert self.header._get_packed_fingerprint() == std_msgs_Header._get_packed_fingerprint()
        self.header._encode_one(buf)
        __format_encoded = self.format.encode('utf-8')
        buf.write(struct.pack('>I', len(__format_encoded)+1))
        buf.write(__format_encoded)
        buf.write(b"\0")
        buf.write(struct.pack(">q", self.size))
        buf.write(bytearray(self.data[:self.size]))

    def decode(data):
        if hasattr(data, 'read'):
            buf = data
        else:
            buf = BytesIO(data)
        if buf.read(8) != CompressedImage._get_packed_fingerprint():
            raise ValueError("Decode error")
        return CompressedImage._decode_one(buf)
    decode = staticmethod(decode)

    def _decode_one(buf):
        self = CompressedImage()
        self.header = std_msgs_Header._decode_one(buf)
        __format_len = struct.unpack('>I', buf.read(4))[0]
        self.format = buf.read(__format_len)[:-1].decode('utf-8', 'replace')
        self.size = struct.unpack(">q", buf.read(8))[0]
        self.data = buf.read(self.size)
        return self
    _decode_one = staticmethod(_decode_one)

    _hash = None
    def _get_hash_recursive(parents):
        if CompressedImage in parents: return 0
        newparents = parents + [CompressedImage]
        tmphash = (0x2942ce7cd2a1e401+ std_msgs_Header._get_hash_recursive(newparents)) & 0xffffffffffffffff
        tmphash  = (((tmphash<<1)&0xffffffffffffffff)  + ((tmphash>>63)&0x1)) & 0xffffffffffffffff
        return tmphash
    _get_hash_recursive = staticmethod(_get_hash_recursive)
    _packed_fingerprint = None

    def _get_packed_fingerprint():
        if CompressedImage._packed_fingerprint is None:
            CompressedImage._packed_fingerprint = struct.pack(">Q", CompressedImage._get_hash_recursive([]))
        return CompressedImage._packed_fingerprint
    _get_packed_fingerprint = staticmethod(_get_packed_fingerprint)

