"""ZCM type definitions
This file automatically generated by zcm.
DO NOT MODIFY BY HAND!!!!
"""

try:
    import cStringIO.StringIO as BytesIO
except ImportError:
    from io import BytesIO
import struct

from sensor_driver.common_lib.logging.message.geometry_msgs.Vector3 import Vector3 as geometry_msgs_Vector3

from sensor_driver.common_lib.logging.message.geometry_msgs.Quaternion import Quaternion as geometry_msgs_Quaternion

from sensor_driver.common_lib.logging.message.std_msgs.Header import Header as std_msgs_Header

class Imu(object):
    __slots__ = ["header", "orientation", "angular_velocity", "linear_acceleration"]

    IS_LITTLE_ENDIAN = False;
    def __init__(self):
        self.header = std_msgs_Header()
        self.orientation = geometry_msgs_Quaternion()
        self.angular_velocity = geometry_msgs_Vector3()
        self.linear_acceleration = geometry_msgs_Vector3()

    def encode(self):
        buf = BytesIO()
        buf.write(Imu._get_packed_fingerprint())
        self._encode_one(buf)
        return buf.getvalue()

    def _encode_one(self, buf):
        assert self.header._get_packed_fingerprint() == std_msgs_Header._get_packed_fingerprint()
        self.header._encode_one(buf)
        assert self.orientation._get_packed_fingerprint() == geometry_msgs_Quaternion._get_packed_fingerprint()
        self.orientation._encode_one(buf)
        assert self.angular_velocity._get_packed_fingerprint() == geometry_msgs_Vector3._get_packed_fingerprint()
        self.angular_velocity._encode_one(buf)
        assert self.linear_acceleration._get_packed_fingerprint() == geometry_msgs_Vector3._get_packed_fingerprint()
        self.linear_acceleration._encode_one(buf)

    def decode(data):
        if hasattr(data, 'read'):
            buf = data
        else:
            buf = BytesIO(data)
        if buf.read(8) != Imu._get_packed_fingerprint():
            raise ValueError("Decode error")
        return Imu._decode_one(buf)
    decode = staticmethod(decode)

    def _decode_one(buf):
        self = Imu()
        self.header = std_msgs_Header._decode_one(buf)
        self.orientation = geometry_msgs_Quaternion._decode_one(buf)
        self.angular_velocity = geometry_msgs_Vector3._decode_one(buf)
        self.linear_acceleration = geometry_msgs_Vector3._decode_one(buf)
        return self
    _decode_one = staticmethod(_decode_one)

    _hash = None
    def _get_hash_recursive(parents):
        if Imu in parents: return 0
        newparents = parents + [Imu]
        tmphash = (0x3496d752468acf0+ std_msgs_Header._get_hash_recursive(newparents)+ geometry_msgs_Quaternion._get_hash_recursive(newparents)+ geometry_msgs_Vector3._get_hash_recursive(newparents)+ geometry_msgs_Vector3._get_hash_recursive(newparents)) & 0xffffffffffffffff
        tmphash  = (((tmphash<<1)&0xffffffffffffffff)  + ((tmphash>>63)&0x1)) & 0xffffffffffffffff
        return tmphash
    _get_hash_recursive = staticmethod(_get_hash_recursive)
    _packed_fingerprint = None

    def _get_packed_fingerprint():
        if Imu._packed_fingerprint is None:
            Imu._packed_fingerprint = struct.pack(">Q", Imu._get_hash_recursive([]))
        return Imu._packed_fingerprint
    _get_packed_fingerprint = staticmethod(_get_packed_fingerprint)

