/** THIS IS AN AUTOMATICALLY GENERATED FILE.
 *  DO NOT MODIFY BY HAND!!
 *
 *  Generated by zcm-gen
 **/

#include <zcm/zcm_coretypes.h>

#ifndef __sensor_msgs_NavSatFix_hpp__
#define __sensor_msgs_NavSatFix_hpp__

#include "std_msgs/Header.hpp"
#include "sensor_msgs/NavSatStatus.hpp"


namespace sensor_msgs {
class NavSatFix
{
    public:
        std_msgs::Header header;

        sensor_msgs::NavSatStatus status;

        double     latitude;

        double     longitude;

        double     altitude;

        double     position_covariance[64];

        int8_t     position_covariance_type;

    public:
        #if __cplusplus > 199711L /* if c++11 */
        static constexpr int8_t      IS_LITTLE_ENDIAN = 0;
        static constexpr int8_t      COVARIANCE_TYPE_UNKNOWN = 0;
        static constexpr int8_t      COVARIANCE_TYPE_APPROXIMATED = 1;
        static constexpr int8_t      COVARIANCE_TYPE_DIAGONAL_KNOWN = 2;
        static constexpr int8_t      COVARIANCE_TYPE_KNOWN = 3;
        #else
        static const     int8_t      IS_LITTLE_ENDIAN = 0;
        static const     int8_t      COVARIANCE_TYPE_UNKNOWN = 0;
        static const     int8_t      COVARIANCE_TYPE_APPROXIMATED = 1;
        static const     int8_t      COVARIANCE_TYPE_DIAGONAL_KNOWN = 2;
        static const     int8_t      COVARIANCE_TYPE_KNOWN = 3;
        #endif

    public:
        /**
         * Destructs a message properly if anything inherits from it
        */
        virtual ~NavSatFix() {}

        /**
         * Encode a message into binary form.
         *
         * @param buf The output buffer.
         * @param offset Encoding starts at thie byte offset into @p buf.
         * @param maxlen Maximum number of bytes to write.  This should generally be
         *  equal to getEncodedSize().
         * @return The number of bytes encoded, or <0 on error.
         */
        inline int encode(void* buf, uint32_t offset, uint32_t maxlen) const;

        /**
         * Check how many bytes are required to encode this message.
         */
        inline uint32_t getEncodedSize() const;

        /**
         * Decode a message from binary form into this instance.
         *
         * @param buf The buffer containing the encoded message.
         * @param offset The byte offset into @p buf where the encoded message starts.
         * @param maxlen The maximum number of bytes to read while decoding.
         * @return The number of bytes decoded, or <0 if an error occured.
         */
        inline int decode(const void* buf, uint32_t offset, uint32_t maxlen);

        /**
         * Retrieve the 64-bit fingerprint identifying the structure of the message.
         * Note that the fingerprint is the same for all instances of the same
         * message type, and is a fingerprint on the message type definition, not on
         * the message contents.
         */
        inline static int64_t getHash();

        /**
         * Returns "NavSatFix"
         */
        inline static const char* getTypeName();

        // ZCM support functions. Users should not call these
        inline int      _encodeNoHash(void* buf, uint32_t offset, uint32_t maxlen) const;
        inline uint32_t _getEncodedSizeNoHash() const;
        inline int      _decodeNoHash(const void* buf, uint32_t offset, uint32_t maxlen);
        inline static uint64_t _computeHash(const __zcm_hash_ptr* p);
};

int NavSatFix::encode(void* buf, uint32_t offset, uint32_t maxlen) const
{
    uint32_t pos = 0;
    int thislen;
    int64_t hash = (int64_t)getHash();

    thislen = __int64_t_encode_array(buf, offset + pos, maxlen - pos, &hash, 1);
    if(thislen < 0) return thislen; else pos += thislen;

    thislen = this->_encodeNoHash(buf, offset + pos, maxlen - pos);
    if (thislen < 0) return thislen; else pos += thislen;

    return pos;
}

int NavSatFix::decode(const void* buf, uint32_t offset, uint32_t maxlen)
{
    uint32_t pos = 0;
    int thislen;

    int64_t msg_hash;
    thislen = __int64_t_decode_array(buf, offset + pos, maxlen - pos, &msg_hash, 1);
    if (thislen < 0) return thislen; else pos += thislen;
    if (msg_hash != getHash()) return -1;

    thislen = this->_decodeNoHash(buf, offset + pos, maxlen - pos);
    if (thislen < 0) return thislen; else pos += thislen;

    return pos;
}

uint32_t NavSatFix::getEncodedSize() const
{
    return 8 + _getEncodedSizeNoHash();
}

int64_t NavSatFix::getHash()
{
    static int64_t hash = _computeHash(NULL);
    return hash;
}

const char* NavSatFix::getTypeName()
{
    return "NavSatFix";
}

int NavSatFix::_encodeNoHash(void* buf, uint32_t offset, uint32_t maxlen) const
{
    uint32_t pos_byte = 0;
    int thislen;

    thislen = this->header._encodeNoHash(buf, offset + pos_byte, maxlen - pos_byte);
    if(thislen < 0) return thislen; else pos_byte += thislen;

    thislen = this->status._encodeNoHash(buf, offset + pos_byte, maxlen - pos_byte);
    if(thislen < 0) return thislen; else pos_byte += thislen;

    thislen = __double_encode_array(buf, offset + pos_byte, maxlen - pos_byte, &this->latitude, 1);
    if(thislen < 0) return thislen; else pos_byte += thislen;

    thislen = __double_encode_array(buf, offset + pos_byte, maxlen - pos_byte, &this->longitude, 1);
    if(thislen < 0) return thislen; else pos_byte += thislen;

    thislen = __double_encode_array(buf, offset + pos_byte, maxlen - pos_byte, &this->altitude, 1);
    if(thislen < 0) return thislen; else pos_byte += thislen;

    thislen = __double_encode_array(buf, offset + pos_byte, maxlen - pos_byte, &this->position_covariance[0], 64);
    if(thislen < 0) return thislen; else pos_byte += thislen;

    thislen = __int8_t_encode_array(buf, offset + pos_byte, maxlen - pos_byte, &this->position_covariance_type, 1);
    if(thislen < 0) return thislen; else pos_byte += thislen;

    return pos_byte;
}

int NavSatFix::_decodeNoHash(const void* buf, uint32_t offset, uint32_t maxlen)
{
    uint32_t pos_byte = 0;
    int thislen;

    thislen = this->header._decodeNoHash(buf, offset + pos_byte, maxlen - pos_byte);
    if(thislen < 0) return thislen; else pos_byte += thislen;

    thislen = this->status._decodeNoHash(buf, offset + pos_byte, maxlen - pos_byte);
    if(thislen < 0) return thislen; else pos_byte += thislen;

    thislen = __double_decode_array(buf, offset + pos_byte, maxlen - pos_byte, &this->latitude, 1);
    if(thislen < 0) return thislen; else pos_byte += thislen;

    thislen = __double_decode_array(buf, offset + pos_byte, maxlen - pos_byte, &this->longitude, 1);
    if(thislen < 0) return thislen; else pos_byte += thislen;

    thislen = __double_decode_array(buf, offset + pos_byte, maxlen - pos_byte, &this->altitude, 1);
    if(thislen < 0) return thislen; else pos_byte += thislen;

    thislen = __double_decode_array(buf, offset + pos_byte, maxlen - pos_byte, &this->position_covariance[0], 64);
    if(thislen < 0) return thislen; else pos_byte += thislen;

    thislen = __int8_t_decode_array(buf, offset + pos_byte, maxlen - pos_byte, &this->position_covariance_type, 1);
    if(thislen < 0) return thislen; else pos_byte += thislen;

    return pos_byte;
}

uint32_t NavSatFix::_getEncodedSizeNoHash() const
{
    uint32_t enc_size = 0;
    enc_size += this->header._getEncodedSizeNoHash();
    enc_size += this->status._getEncodedSizeNoHash();
    enc_size += __double_encoded_array_size(NULL, 1);
    enc_size += __double_encoded_array_size(NULL, 1);
    enc_size += __double_encoded_array_size(NULL, 1);
    enc_size += __double_encoded_array_size(NULL, 64);
    enc_size += __int8_t_encoded_array_size(NULL, 1);
    return enc_size;
}

uint64_t NavSatFix::_computeHash(const __zcm_hash_ptr* p)
{
    const __zcm_hash_ptr* fp;
    for(fp = p; fp != NULL; fp = fp->parent)
        if(fp->v == NavSatFix::getHash)
            return 0;
    const __zcm_hash_ptr cp = { p, (void*)NavSatFix::getHash };

    uint64_t hash = (uint64_t)0xa6e2262989466c08LL +
         std_msgs::Header::_computeHash(&cp) +
         sensor_msgs::NavSatStatus::_computeHash(&cp);

    return (hash<<1) + ((hash>>63)&1);
}

}

#endif
