"""ZCM type definitions
This file automatically generated by zcm.
DO NOT MODIFY BY HAND!!!!
"""

try:
    import cStringIO.StringIO as BytesIO
except ImportError:
    from io import BytesIO
import struct

class PointField(object):
    __slots__ = ["name", "offset", "datatype", "count"]

    IS_LITTLE_ENDIAN = False;
    INT8 = 1;
    UINT8 = 2;
    INT16 = 3;
    UINT16 = 4;
    INT32 = 5;
    UINT32 = 6;
    FLOAT32 = 7;
    FLOAT64 = 8;

    def __init__(self):
        self.name = ""
        self.offset = 0
        self.datatype = 0
        self.count = 0

    def encode(self):
        buf = BytesIO()
        buf.write(PointField._get_packed_fingerprint())
        self._encode_one(buf)
        return buf.getvalue()

    def _encode_one(self, buf):
        __name_encoded = self.name.encode('utf-8')
        buf.write(struct.pack('>I', len(__name_encoded)+1))
        buf.write(__name_encoded)
        buf.write(b"\0")
        buf.write(struct.pack(">ibi", self.offset, self.datatype, self.count))

    def decode(data):
        if hasattr(data, 'read'):
            buf = data
        else:
            buf = BytesIO(data)
        if buf.read(8) != PointField._get_packed_fingerprint():
            raise ValueError("Decode error")
        return PointField._decode_one(buf)
    decode = staticmethod(decode)

    def _decode_one(buf):
        self = PointField()
        __name_len = struct.unpack('>I', buf.read(4))[0]
        self.name = buf.read(__name_len)[:-1].decode('utf-8', 'replace')
        self.offset, self.datatype, self.count = struct.unpack(">ibi", buf.read(9))
        return self
    _decode_one = staticmethod(_decode_one)

    _hash = None
    def _get_hash_recursive(parents):
        if PointField in parents: return 0
        tmphash = (0xa9fb1155ff313fdd) & 0xffffffffffffffff
        tmphash  = (((tmphash<<1)&0xffffffffffffffff)  + ((tmphash>>63)&0x1)) & 0xffffffffffffffff
        return tmphash
    _get_hash_recursive = staticmethod(_get_hash_recursive)
    _packed_fingerprint = None

    def _get_packed_fingerprint():
        if PointField._packed_fingerprint is None:
            PointField._packed_fingerprint = struct.pack(">Q", PointField._get_hash_recursive([]))
        return PointField._packed_fingerprint
    _get_packed_fingerprint = staticmethod(_get_packed_fingerprint)

