/** THIS IS AN AUTOMATICALLY GENERATED FILE.
 *  DO NOT MODIFY BY HAND!!
 *
 *  Generated by zcm-gen
 **/

#include <zcm/zcm_coretypes.h>

#ifndef __sensor_msgs_PointCloud_hpp__
#define __sensor_msgs_PointCloud_hpp__

#include <vector>
#include "std_msgs/Header.hpp"
#include "sensor_msgs/PointField.hpp"


namespace sensor_msgs {
class PointCloud
{
    public:
        std_msgs::Header header;

        int32_t    height;

        int32_t    width;

        int32_t    fields_num;

        std::vector< sensor_msgs::PointField > fields;

        int8_t     is_bigendian;

        int32_t    point_step;

        int32_t    row_step;

        int64_t    data_num;

        std::vector< uint8_t > data;

        int8_t     is_dense;

    public:
        /**
         * Destructs a message properly if anything inherits from it
        */
        virtual ~PointCloud() {}

        /**
         * Encode a message into binary form.
         *
         * @param buf The output buffer.
         * @param offset Encoding starts at thie byte offset into @p buf.
         * @param maxlen Maximum number of bytes to write.  This should generally be
         *  equal to getEncodedSize().
         * @return The number of bytes encoded, or <0 on error.
         */
        inline int encode(void* buf, uint32_t offset, uint32_t maxlen) const;

        /**
         * Check how many bytes are required to encode this message.
         */
        inline uint32_t getEncodedSize() const;

        /**
         * Decode a message from binary form into this instance.
         *
         * @param buf The buffer containing the encoded message.
         * @param offset The byte offset into @p buf where the encoded message starts.
         * @param maxlen The maximum number of bytes to read while decoding.
         * @return The number of bytes decoded, or <0 if an error occured.
         */
        inline int decode(const void* buf, uint32_t offset, uint32_t maxlen);

        /**
         * Retrieve the 64-bit fingerprint identifying the structure of the message.
         * Note that the fingerprint is the same for all instances of the same
         * message type, and is a fingerprint on the message type definition, not on
         * the message contents.
         */
        inline static int64_t getHash();

        /**
         * Returns "PointCloud"
         */
        inline static const char* getTypeName();

        // ZCM support functions. Users should not call these
        inline int      _encodeNoHash(void* buf, uint32_t offset, uint32_t maxlen) const;
        inline uint32_t _getEncodedSizeNoHash() const;
        inline int      _decodeNoHash(const void* buf, uint32_t offset, uint32_t maxlen);
        inline static uint64_t _computeHash(const __zcm_hash_ptr* p);
};

int PointCloud::encode(void* buf, uint32_t offset, uint32_t maxlen) const
{
    uint32_t pos = 0;
    int thislen;
    int64_t hash = (int64_t)getHash();

    thislen = __int64_t_encode_array(buf, offset + pos, maxlen - pos, &hash, 1);
    if(thislen < 0) return thislen; else pos += thislen;

    thislen = this->_encodeNoHash(buf, offset + pos, maxlen - pos);
    if (thislen < 0) return thislen; else pos += thislen;

    return pos;
}

int PointCloud::decode(const void* buf, uint32_t offset, uint32_t maxlen)
{
    uint32_t pos = 0;
    int thislen;

    int64_t msg_hash;
    thislen = __int64_t_decode_array(buf, offset + pos, maxlen - pos, &msg_hash, 1);
    if (thislen < 0) return thislen; else pos += thislen;
    if (msg_hash != getHash()) return -1;

    thislen = this->_decodeNoHash(buf, offset + pos, maxlen - pos);
    if (thislen < 0) return thislen; else pos += thislen;

    return pos;
}

uint32_t PointCloud::getEncodedSize() const
{
    return 8 + _getEncodedSizeNoHash();
}

int64_t PointCloud::getHash()
{
    static int64_t hash = _computeHash(NULL);
    return hash;
}

const char* PointCloud::getTypeName()
{
    return "PointCloud";
}

int PointCloud::_encodeNoHash(void* buf, uint32_t offset, uint32_t maxlen) const
{
    uint32_t pos_byte = 0;
    int thislen;

    thislen = this->header._encodeNoHash(buf, offset + pos_byte, maxlen - pos_byte);
    if(thislen < 0) return thislen; else pos_byte += thislen;

    thislen = __int32_t_encode_array(buf, offset + pos_byte, maxlen - pos_byte, &this->height, 1);
    if(thislen < 0) return thislen; else pos_byte += thislen;

    thislen = __int32_t_encode_array(buf, offset + pos_byte, maxlen - pos_byte, &this->width, 1);
    if(thislen < 0) return thislen; else pos_byte += thislen;

    thislen = __int32_t_encode_array(buf, offset + pos_byte, maxlen - pos_byte, &this->fields_num, 1);
    if(thislen < 0) return thislen; else pos_byte += thislen;

    for (int a0 = 0; a0 < this->fields_num; ++a0) {
        thislen = this->fields[a0]._encodeNoHash(buf, offset + pos_byte, maxlen - pos_byte);
        if(thislen < 0) return thislen; else pos_byte += thislen;
    }

    thislen = __boolean_encode_array(buf, offset + pos_byte, maxlen - pos_byte, &this->is_bigendian, 1);
    if(thislen < 0) return thislen; else pos_byte += thislen;

    thislen = __int32_t_encode_array(buf, offset + pos_byte, maxlen - pos_byte, &this->point_step, 1);
    if(thislen < 0) return thislen; else pos_byte += thislen;

    thislen = __int32_t_encode_array(buf, offset + pos_byte, maxlen - pos_byte, &this->row_step, 1);
    if(thislen < 0) return thislen; else pos_byte += thislen;

    thislen = __int64_t_encode_array(buf, offset + pos_byte, maxlen - pos_byte, &this->data_num, 1);
    if(thislen < 0) return thislen; else pos_byte += thislen;

    if(this->data_num > 0) {
        thislen = __byte_encode_array(buf, offset + pos_byte, maxlen - pos_byte, &this->data[0], this->data_num);
        if(thislen < 0) return thislen; else pos_byte += thislen;
    }

    thislen = __boolean_encode_array(buf, offset + pos_byte, maxlen - pos_byte, &this->is_dense, 1);
    if(thislen < 0) return thislen; else pos_byte += thislen;

    return pos_byte;
}

int PointCloud::_decodeNoHash(const void* buf, uint32_t offset, uint32_t maxlen)
{
    uint32_t pos_byte = 0;
    int thislen;

    thislen = this->header._decodeNoHash(buf, offset + pos_byte, maxlen - pos_byte);
    if(thislen < 0) return thislen; else pos_byte += thislen;

    thislen = __int32_t_decode_array(buf, offset + pos_byte, maxlen - pos_byte, &this->height, 1);
    if(thislen < 0) return thislen; else pos_byte += thislen;

    thislen = __int32_t_decode_array(buf, offset + pos_byte, maxlen - pos_byte, &this->width, 1);
    if(thislen < 0) return thislen; else pos_byte += thislen;

    thislen = __int32_t_decode_array(buf, offset + pos_byte, maxlen - pos_byte, &this->fields_num, 1);
    if(thislen < 0) return thislen; else pos_byte += thislen;

    this->fields.resize(this->fields_num);
    for (int a0 = 0; a0 < this->fields_num; ++a0) {
        thislen = this->fields[a0]._decodeNoHash(buf, offset + pos_byte, maxlen - pos_byte);
        if(thislen < 0) return thislen; else pos_byte += thislen;
    }

    thislen = __boolean_decode_array(buf, offset + pos_byte, maxlen - pos_byte, &this->is_bigendian, 1);
    if(thislen < 0) return thislen; else pos_byte += thislen;

    thislen = __int32_t_decode_array(buf, offset + pos_byte, maxlen - pos_byte, &this->point_step, 1);
    if(thislen < 0) return thislen; else pos_byte += thislen;

    thislen = __int32_t_decode_array(buf, offset + pos_byte, maxlen - pos_byte, &this->row_step, 1);
    if(thislen < 0) return thislen; else pos_byte += thislen;

    thislen = __int64_t_decode_array(buf, offset + pos_byte, maxlen - pos_byte, &this->data_num, 1);
    if(thislen < 0) return thislen; else pos_byte += thislen;

    if(this->data_num > 0) {
        this->data.resize(this->data_num);
        thislen = __byte_decode_array(buf, offset + pos_byte, maxlen - pos_byte, &this->data[0], this->data_num);
        if(thislen < 0) return thislen; else pos_byte += thislen;
    }

    thislen = __boolean_decode_array(buf, offset + pos_byte, maxlen - pos_byte, &this->is_dense, 1);
    if(thislen < 0) return thislen; else pos_byte += thislen;

    return pos_byte;
}

uint32_t PointCloud::_getEncodedSizeNoHash() const
{
    uint32_t enc_size = 0;
    enc_size += this->header._getEncodedSizeNoHash();
    enc_size += __int32_t_encoded_array_size(NULL, 1);
    enc_size += __int32_t_encoded_array_size(NULL, 1);
    enc_size += __int32_t_encoded_array_size(NULL, 1);
    for (int a0 = 0; a0 < this->fields_num; ++a0) {
        enc_size += this->fields[a0]._getEncodedSizeNoHash();
    }
    enc_size += __boolean_encoded_array_size(NULL, 1);
    enc_size += __int32_t_encoded_array_size(NULL, 1);
    enc_size += __int32_t_encoded_array_size(NULL, 1);
    enc_size += __int64_t_encoded_array_size(NULL, 1);
    enc_size += __byte_encoded_array_size(NULL, this->data_num);
    enc_size += __boolean_encoded_array_size(NULL, 1);
    return enc_size;
}

uint64_t PointCloud::_computeHash(const __zcm_hash_ptr* p)
{
    const __zcm_hash_ptr* fp;
    for(fp = p; fp != NULL; fp = fp->parent)
        if(fp->v == PointCloud::getHash)
            return 0;
    const __zcm_hash_ptr cp = { p, (void*)PointCloud::getHash };

    uint64_t hash = (uint64_t)0x09e56935c3ca382eLL +
         std_msgs::Header::_computeHash(&cp) +
         sensor_msgs::PointField::_computeHash(&cp);

    return (hash<<1) + ((hash>>63)&1);
}

}

#endif
