// THIS IS AN AUTOMATICALLY GENERATED FILE.
// DO NOT MODIFY BY HAND!!
//
// Generated by zcm-gen

#include <stdint.h>
#include <stdlib.h>
#include <zcm/zcm_coretypes.h>
#include <zcm/zcm.h>

#ifndef _sensor_msgs_PointField_h
#define _sensor_msgs_PointField_h

#ifdef __cplusplus
extern "C" {
#endif

#define SENSOR_MSGS_POINTFIELD_IS_LITTLE_ENDIAN 0
#define SENSOR_MSGS_POINTFIELD_INT8 ((int8_t)1)
#define SENSOR_MSGS_POINTFIELD_UINT8 ((int8_t)2)
#define SENSOR_MSGS_POINTFIELD_INT16 ((int8_t)3)
#define SENSOR_MSGS_POINTFIELD_UINT16 ((int8_t)4)
#define SENSOR_MSGS_POINTFIELD_INT32 ((int8_t)5)
#define SENSOR_MSGS_POINTFIELD_UINT32 ((int8_t)6)
#define SENSOR_MSGS_POINTFIELD_FLOAT32 ((int8_t)7)
#define SENSOR_MSGS_POINTFIELD_FLOAT64 ((int8_t)8)

typedef struct _sensor_msgs_PointField sensor_msgs_PointField;
struct _sensor_msgs_PointField
{
    char*      name;
    int32_t    offset;
    int8_t     datatype;
    int32_t    count;
};

/**
 * Create a deep copy of a sensor_msgs_PointField.
 * When no longer needed, destroy it with sensor_msgs_PointField_destroy()
 */
sensor_msgs_PointField* sensor_msgs_PointField_copy(const sensor_msgs_PointField* to_copy);

/**
 * Destroy an instance of sensor_msgs_PointField created by sensor_msgs_PointField_copy()
 */
void sensor_msgs_PointField_destroy(sensor_msgs_PointField* to_destroy);

/**
 * Identifies a single subscription.  This is an opaque data type.
 */
typedef struct _sensor_msgs_PointField_subscription_t sensor_msgs_PointField_subscription_t;

/**
 * Prototype for a callback function invoked when a message of type
 * sensor_msgs_PointField is received.
 */
typedef void(*sensor_msgs_PointField_handler_t)(const zcm_recv_buf_t* rbuf,
             const char* channel, const sensor_msgs_PointField* msg, void* userdata);

/**
 * Publish a message of type sensor_msgs_PointField using ZCM.
 *
 * @param zcm The ZCM instance to publish with.
 * @param channel The channel to publish on.
 * @param msg The message to publish.
 * @return 0 on success, <0 on error.  Success means ZCM has transferred
 * responsibility of the message data to the OS.
 */
int sensor_msgs_PointField_publish(zcm_t* zcm, const char* channel, const sensor_msgs_PointField* msg);

/**
 * Subscribe to messages of type sensor_msgs_PointField using ZCM.
 *
 * @param zcm The ZCM instance to subscribe with.
 * @param channel The channel to subscribe to.
 * @param handler The callback function invoked by ZCM when a message is received.
 *                This function is invoked by ZCM during calls to zcm_handle() and
 *                zcm_handle_timeout().
 * @param userdata An opaque pointer passed to @p handler when it is invoked.
 * @return pointer to subscription type, NULL if failure. Must clean up
 *         dynamic memory by passing the pointer to sensor_msgs_PointField_unsubscribe.
 */
sensor_msgs_PointField_subscription_t* sensor_msgs_PointField_subscribe(zcm_t* zcm, const char* channel, sensor_msgs_PointField_handler_t handler, void* userdata);

/**
 * Removes and destroys a subscription created by sensor_msgs_PointField_subscribe()
 */
int sensor_msgs_PointField_unsubscribe(zcm_t* zcm, sensor_msgs_PointField_subscription_t* hid);
/**
 * Encode a message of type sensor_msgs_PointField into binary form.
 *
 * @param buf The output buffer.
 * @param offset Encoding starts at this byte offset into @p buf.
 * @param maxlen Maximum number of bytes to write.  This should generally
 *               be equal to sensor_msgs_PointField_encoded_size().
 * @param msg The message to encode.
 * @return The number of bytes encoded, or <0 if an error occured.
 */
int sensor_msgs_PointField_encode(void* buf, uint32_t offset, uint32_t maxlen, const sensor_msgs_PointField* p);

/**
 * Decode a message of type sensor_msgs_PointField from binary form.
 * When decoding messages containing strings or variable-length arrays, this
 * function may allocate memory.  When finished with the decoded message,
 * release allocated resources with sensor_msgs_PointField_decode_cleanup().
 *
 * @param buf The buffer containing the encoded message
 * @param offset The byte offset into @p buf where the encoded message starts.
 * @param maxlen The maximum number of bytes to read while decoding.
 * @param msg Output parameter where the decoded message is stored
 * @return The number of bytes decoded, or <0 if an error occured.
 */
int sensor_msgs_PointField_decode(const void* buf, uint32_t offset, uint32_t maxlen, sensor_msgs_PointField* msg);

/**
 * Release resources allocated by sensor_msgs_PointField_decode()
 * @return 0
 */
int sensor_msgs_PointField_decode_cleanup(sensor_msgs_PointField* p);

/**
 * Check how many bytes are required to encode a message of type sensor_msgs_PointField
 */
uint32_t sensor_msgs_PointField_encoded_size(const sensor_msgs_PointField* p);
uint32_t sensor_msgs_PointField_struct_size(void);
uint32_t sensor_msgs_PointField_num_fields(void);
int      sensor_msgs_PointField_get_field(const sensor_msgs_PointField* p, uint32_t i, zcm_field_t* f);
const zcm_type_info_t* sensor_msgs_PointField_get_type_info(void);

// ZCM support functions. Users should not call these
int64_t  __sensor_msgs_PointField_get_hash(void);
uint64_t __sensor_msgs_PointField_hash_recursive(const __zcm_hash_ptr* p);
int      __sensor_msgs_PointField_encode_array(void* buf, uint32_t offset, uint32_t maxlen, const sensor_msgs_PointField* p, uint32_t elements);
int      __sensor_msgs_PointField_decode_array(const void* buf, uint32_t offset, uint32_t maxlen, sensor_msgs_PointField* p, uint32_t elements);
int      __sensor_msgs_PointField_decode_array_cleanup(sensor_msgs_PointField* p, uint32_t elements);
uint32_t __sensor_msgs_PointField_encoded_array_size(const sensor_msgs_PointField* p, uint32_t elements);
uint32_t __sensor_msgs_PointField_clone_array(const sensor_msgs_PointField* p, sensor_msgs_PointField* q, uint32_t elements);

#ifdef __cplusplus
}
#endif

#endif
