// THIS IS AN AUTOMATICALLY GENERATED FILE.
// DO NOT MODIFY BY HAND!!
//
// Generated by zcm-gen

#include <string.h>
#ifndef ZCM_EMBEDDED
#include <stdio.h>
#endif
#include "sensor_msgs/sensor_msgs_Imu.h"

static int __sensor_msgs_Imu_hash_computed = 0;
static uint64_t __sensor_msgs_Imu_hash;

uint64_t __sensor_msgs_Imu_hash_recursive(const __zcm_hash_ptr* p)
{
    const __zcm_hash_ptr* fp;
    for (fp = p; fp != NULL; fp = fp->parent)
        if (fp->v == __sensor_msgs_Imu_get_hash)
            return 0;

    __zcm_hash_ptr cp;
    cp.parent =  p;
    cp.v = (void*)__sensor_msgs_Imu_get_hash;
    (void) cp;

    uint64_t hash = (uint64_t)0x03496d752468acf0LL
         + __std_msgs_Header_hash_recursive(&cp)
         + __geometry_msgs_Quaternion_hash_recursive(&cp)
         + __geometry_msgs_Vector3_hash_recursive(&cp)
         + __geometry_msgs_Vector3_hash_recursive(&cp)
        ;

    return (hash<<1) + ((hash>>63)&1);
}

int64_t __sensor_msgs_Imu_get_hash(void)
{
    if (!__sensor_msgs_Imu_hash_computed) {
        __sensor_msgs_Imu_hash = (int64_t)__sensor_msgs_Imu_hash_recursive(NULL);
        __sensor_msgs_Imu_hash_computed = 1;
    }

    return __sensor_msgs_Imu_hash;
}

int __sensor_msgs_Imu_encode_array(void* buf, uint32_t offset, uint32_t maxlen, const sensor_msgs_Imu* p, uint32_t elements)
{
    uint32_t pos_byte = 0, element;
    int thislen;

    for (element = 0; element < elements; ++element) {

        /* header */
        thislen = __std_msgs_Header_encode_array(buf, offset + pos_byte, maxlen - pos_byte, &(p[element].header), 1);
        if (thislen < 0) return thislen; else pos_byte += thislen;

        /* orientation */
        thislen = __geometry_msgs_Quaternion_encode_array(buf, offset + pos_byte, maxlen - pos_byte, &(p[element].orientation), 1);
        if (thislen < 0) return thislen; else pos_byte += thislen;

        /* angular_velocity */
        thislen = __geometry_msgs_Vector3_encode_array(buf, offset + pos_byte, maxlen - pos_byte, &(p[element].angular_velocity), 1);
        if (thislen < 0) return thislen; else pos_byte += thislen;

        /* linear_acceleration */
        thislen = __geometry_msgs_Vector3_encode_array(buf, offset + pos_byte, maxlen - pos_byte, &(p[element].linear_acceleration), 1);
        if (thislen < 0) return thislen; else pos_byte += thislen;

    }
    return pos_byte;
}

int sensor_msgs_Imu_encode(void* buf, uint32_t offset, uint32_t maxlen, const sensor_msgs_Imu* p)
{
    uint32_t pos = 0;
    int thislen;
    int64_t hash = __sensor_msgs_Imu_get_hash();

    thislen = __int64_t_encode_array(buf, offset + pos, maxlen - pos, &hash, 1);
    if (thislen < 0) return thislen; else pos += thislen;

    thislen = __sensor_msgs_Imu_encode_array(buf, offset + pos, maxlen - pos, p, 1);
    if (thislen < 0) return thislen; else pos += thislen;

    return pos;
}

uint32_t __sensor_msgs_Imu_encoded_array_size(const sensor_msgs_Imu* p, uint32_t elements)
{
    uint32_t size = 0, element;
    for (element = 0; element < elements; ++element) {

        size += __std_msgs_Header_encoded_array_size(&(p[element].header), 1); // header

        size += __geometry_msgs_Quaternion_encoded_array_size(&(p[element].orientation), 1); // orientation

        size += __geometry_msgs_Vector3_encoded_array_size(&(p[element].angular_velocity), 1); // angular_velocity

        size += __geometry_msgs_Vector3_encoded_array_size(&(p[element].linear_acceleration), 1); // linear_acceleration

    }
    return size;
}

uint32_t sensor_msgs_Imu_encoded_size(const sensor_msgs_Imu* p)
{
    return 8 + __sensor_msgs_Imu_encoded_array_size(p, 1);
}

uint32_t sensor_msgs_Imu_struct_size(void)
{
    return sizeof(sensor_msgs_Imu);
}

uint32_t sensor_msgs_Imu_num_fields(void)
{
    return 4;
}

int sensor_msgs_Imu_get_field(const sensor_msgs_Imu* p, uint32_t i, zcm_field_t* f)
{
    if (i >= sensor_msgs_Imu_num_fields())
        return 1;
    
    switch (i) {
    
        case 0: {
            /* Header */
            f->name = "header";
            f->type = ZCM_FIELD_USER_TYPE;
            f->typestr = "std_msgs.Header";
            f->num_dim = 0;
            f->data = (void*) &p->header;
            return 0;
        }
        
        case 1: {
            /* Quaternion */
            f->name = "orientation";
            f->type = ZCM_FIELD_USER_TYPE;
            f->typestr = "geometry_msgs.Quaternion";
            f->num_dim = 0;
            f->data = (void*) &p->orientation;
            return 0;
        }
        
        case 2: {
            /* Vector3 */
            f->name = "angular_velocity";
            f->type = ZCM_FIELD_USER_TYPE;
            f->typestr = "geometry_msgs.Vector3";
            f->num_dim = 0;
            f->data = (void*) &p->angular_velocity;
            return 0;
        }
        
        case 3: {
            /* Vector3 */
            f->name = "linear_acceleration";
            f->type = ZCM_FIELD_USER_TYPE;
            f->typestr = "geometry_msgs.Vector3";
            f->num_dim = 0;
            f->data = (void*) &p->linear_acceleration;
            return 0;
        }
        
        default:
            return 1;
    }
}

const zcm_type_info_t* sensor_msgs_Imu_get_type_info(void)
{
    static int init = 0;
    static zcm_type_info_t typeinfo;
    if (!init) {
        typeinfo.encode         = (zcm_encode_t) sensor_msgs_Imu_encode;
        typeinfo.decode         = (zcm_decode_t) sensor_msgs_Imu_decode;
        typeinfo.decode_cleanup = (zcm_decode_cleanup_t) sensor_msgs_Imu_decode_cleanup;
        typeinfo.encoded_size   = (zcm_encoded_size_t) sensor_msgs_Imu_encoded_size;
        typeinfo.struct_size    = (zcm_struct_size_t)  sensor_msgs_Imu_struct_size;
        typeinfo.num_fields     = (zcm_num_fields_t) sensor_msgs_Imu_num_fields;
        typeinfo.get_field      = (zcm_get_field_t) sensor_msgs_Imu_get_field;
        typeinfo.get_hash       = (zcm_get_hash_t) __sensor_msgs_Imu_get_hash;
    }
    
    return &typeinfo;
}

int __sensor_msgs_Imu_decode_array(const void* buf, uint32_t offset, uint32_t maxlen, sensor_msgs_Imu* p, uint32_t elements)
{
    uint32_t pos_byte = 0, element;
    int thislen;

    for (element = 0; element < elements; ++element) {

        /* header */
        thislen = __std_msgs_Header_decode_array(buf, offset + pos_byte, maxlen - pos_byte, &(p[element].header), 1);
        if (thislen < 0) return thislen; else pos_byte += thislen;

        /* orientation */
        thislen = __geometry_msgs_Quaternion_decode_array(buf, offset + pos_byte, maxlen - pos_byte, &(p[element].orientation), 1);
        if (thislen < 0) return thislen; else pos_byte += thislen;

        /* angular_velocity */
        thislen = __geometry_msgs_Vector3_decode_array(buf, offset + pos_byte, maxlen - pos_byte, &(p[element].angular_velocity), 1);
        if (thislen < 0) return thislen; else pos_byte += thislen;

        /* linear_acceleration */
        thislen = __geometry_msgs_Vector3_decode_array(buf, offset + pos_byte, maxlen - pos_byte, &(p[element].linear_acceleration), 1);
        if (thislen < 0) return thislen; else pos_byte += thislen;

    }
    return pos_byte;
}

int __sensor_msgs_Imu_decode_array_cleanup(sensor_msgs_Imu* p, uint32_t elements)
{
    uint32_t element;
    for (element = 0; element < elements; ++element) {

        __std_msgs_Header_decode_array_cleanup(&(p[element].header), 1);

        __geometry_msgs_Quaternion_decode_array_cleanup(&(p[element].orientation), 1);

        __geometry_msgs_Vector3_decode_array_cleanup(&(p[element].angular_velocity), 1);

        __geometry_msgs_Vector3_decode_array_cleanup(&(p[element].linear_acceleration), 1);

    }
    return 0;
}

int sensor_msgs_Imu_decode(const void* buf, uint32_t offset, uint32_t maxlen, sensor_msgs_Imu* p)
{
    uint32_t pos = 0;
    int thislen;
    int64_t hash = __sensor_msgs_Imu_get_hash();

    int64_t this_hash;
    thislen = __int64_t_decode_array(buf, offset + pos, maxlen - pos, &this_hash, 1);
    if (thislen < 0) return thislen; else pos += thislen;
    if (this_hash != hash) return -1;

    thislen = __sensor_msgs_Imu_decode_array(buf, offset + pos, maxlen - pos, p, 1);
    if (thislen < 0) return thislen; else pos += thislen;

    return pos;
}

int sensor_msgs_Imu_decode_cleanup(sensor_msgs_Imu* p)
{
    return __sensor_msgs_Imu_decode_array_cleanup(p, 1);
}

uint32_t __sensor_msgs_Imu_clone_array(const sensor_msgs_Imu* p, sensor_msgs_Imu* q, uint32_t elements)
{
    uint32_t n = 0, element;
    for (element = 0; element < elements; ++element) {

        n += __std_msgs_Header_clone_array(&(p[element].header), &(q[element].header), 1);

        n += __geometry_msgs_Quaternion_clone_array(&(p[element].orientation), &(q[element].orientation), 1);

        n += __geometry_msgs_Vector3_clone_array(&(p[element].angular_velocity), &(q[element].angular_velocity), 1);

        n += __geometry_msgs_Vector3_clone_array(&(p[element].linear_acceleration), &(q[element].linear_acceleration), 1);

    }
    return n;
}

sensor_msgs_Imu* sensor_msgs_Imu_copy(const sensor_msgs_Imu* p)
{
    sensor_msgs_Imu* q = (sensor_msgs_Imu*) malloc(sizeof(sensor_msgs_Imu));
    __sensor_msgs_Imu_clone_array(p, q, 1);
    return q;
}

void sensor_msgs_Imu_destroy(sensor_msgs_Imu* p)
{
    __sensor_msgs_Imu_decode_array_cleanup(p, 1);
    free(p);
}

int sensor_msgs_Imu_publish(zcm_t* zcm, const char* channel, const sensor_msgs_Imu* p)
{
      uint32_t max_data_size = sensor_msgs_Imu_encoded_size (p);
      uint8_t* buf = (uint8_t*) malloc (max_data_size);
      if (!buf) return -1;
      int data_size = sensor_msgs_Imu_encode (buf, 0, max_data_size, p);
      if (data_size < 0) {
          free (buf);
          return data_size;
      }
      int status = zcm_publish (zcm, channel, buf, (uint32_t)data_size);
      free (buf);
      return status;
}

struct _sensor_msgs_Imu_subscription_t {
    sensor_msgs_Imu_handler_t user_handler;
    void* userdata;
    zcm_sub_t* z_sub;
};
static
void sensor_msgs_Imu_handler_stub (const zcm_recv_buf_t* rbuf,
                            const char* channel, void* userdata)
{
    int status;
    sensor_msgs_Imu p;
    memset(&p, 0, sizeof(sensor_msgs_Imu));
    status = sensor_msgs_Imu_decode (rbuf->data, 0, rbuf->data_size, &p);
    if (status < 0) {
        #ifndef ZCM_EMBEDDED
        fprintf (stderr, "error %d decoding sensor_msgs_Imu!!!\n", status);
        #endif
        return;
    }

    sensor_msgs_Imu_subscription_t* h = (sensor_msgs_Imu_subscription_t*) userdata;
    h->user_handler (rbuf, channel, &p, h->userdata);

    sensor_msgs_Imu_decode_cleanup (&p);
}

sensor_msgs_Imu_subscription_t* sensor_msgs_Imu_subscribe (zcm_t* zcm,
                    const char* channel,
                    sensor_msgs_Imu_handler_t f, void* userdata)
{
    sensor_msgs_Imu_subscription_t* n = (sensor_msgs_Imu_subscription_t*)
                       malloc(sizeof(sensor_msgs_Imu_subscription_t));
    n->user_handler = f;
    n->userdata = userdata;
    n->z_sub = zcm_subscribe (zcm, channel,
                              sensor_msgs_Imu_handler_stub, n);
    if (n->z_sub == NULL) {
        #ifndef ZCM_EMBEDDED
        fprintf (stderr,"couldn't reg sensor_msgs_Imu ZCM handler!\n");
        #endif
        free (n);
        return NULL;
    }
    return n;
}

int sensor_msgs_Imu_unsubscribe(zcm_t* zcm, sensor_msgs_Imu_subscription_t* hid)
{
    int status = zcm_unsubscribe (zcm, hid->z_sub);
    if (0 != status) {
        #ifndef ZCM_EMBEDDED
        fprintf(stderr,
           "couldn't unsubscribe sensor_msgs_Imu_handler %p!\n", hid);
        #endif
        return -1;
    }
    free (hid);
    return 0;
}

